# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:990c47eb4d87f0600f1e6da62d32bf37c84cf430faf31d78f5df7425a93a0f0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'json'
require 'html_to_markdown_rb'

module HtmlToMarkdown
  # Re-export all public module functions from the native extension
  HtmlToMarkdownRs.methods(false).each do |m|
    define_singleton_method(m) { |*args, **kwargs, &blk| HtmlToMarkdownRs.public_send(m, *args, **kwargs, &blk) }
  end

  # Re-export all constants (classes, structs, etc.) from the native extension
  HtmlToMarkdownRs.constants.each do |c|
    const_set(c, HtmlToMarkdownRs.const_get(c)) unless const_defined?(c)
  end
end
