# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38ff512b96e160400de4b9fa4276aa12f513878ab47573b5ead7bc197d95e314
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = '3.4.0.pre.rc.45'
end
