# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b39bf33b48e3caa4032e0a15cd65942eee73c0737bc73da953307a357d7b4ce7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = '3.4.0.pre.rc.33'
end
