# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dad3e58c14f6b8233bcc04aacf585ac67a8293d00eaff5dc52a22018219eacf4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = '3.4.0.pre.rc.36'
end
