// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:763bb594da86ac68e8cd69eddea73cd8ad16b83d6f21d06102b26c6e2bfcc24a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import HtmlToMarkdownRs

/// E2e tests for category: smoke.
final class SmokeTests: XCTestCase {
    func testSmokeEmptyString() throws {
        // Empty string produces empty output
        let result = try convert("")
        XCTAssertEqual(result.content.trimmingCharacters(in: .whitespaces), "")
    }

    func testSmokeSimpleHeading() throws {
        // H1 heading converts to ATX markdown
        let result = try convert("<h1>Title</h1>")
        XCTAssertTrue(result.content.contains("# Title"), "expected to contain: \("# Title")")
    }

    func testSmokeSimpleParagraph() throws {
        // Simple paragraph converts correctly
        let result = try convert("<p>Hello World</p>")
        XCTAssertEqual(result.content.trimmingCharacters(in: .whitespaces), "Hello World")
        XCTAssertFalse(result.content.isEmpty, "expected non-empty value")
    }

}
