# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:048c75ae74b430ffa33441a8dd7241b1bfe520e31a66eb84709b5ede993ee4c8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = '3.4.0.pre.rc.23'
end
