# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:60883b377337cbb18a3f5bc64a4d818925b577076b9b0e52ec44c2524c4d860f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = '3.4.0.pre.rc.3'
end
