# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6d159e822e16aa605256383d276b5d6e1903f37cf977ef2ec0204663c91805b7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = "3.4.0.pre.rc.19"
end
