// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:78a446672503d08eb40f5864843f82a7466842060d7d06e51b30ccbe3d86d76a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
  },
});
