// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20456a45b05c76d76b03ce172a00262faf6727e0390c28f7b16156805bcba688
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
  },
});
