# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:773f65d7adb227ee57302709f13e28158c7c5e3a5a6b6efc3fddbd277b4505cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: real-world
defmodule E2e.RealWorldTest do
  use ExUnit.Case, async: false

  describe "real_world_blog_post" do
    @tag :skip
    test "Blog post with headings, paragraphs, code blocks, and links converts to readable Markdown" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "real_world_documentation_page" do
    @tag :skip
    test "Documentation page with nested lists, code examples, and blockquotes converts correctly" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "real_world_product_page" do
    @tag :skip
    test "Product page with table, images, and lists converts correctly" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
