// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:65b9c8fe7f96d4879648bb2862495bb28134b889dd7e9427bae378aa705831e2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: conversion
package e2e_test

import (
	"strings"
	"testing"

	htmd "github.com/kreuzberg-dev/html-to-markdown/packages/go/v3"
)

func Test_BlockquoteMultipleParagraphs(t *testing.T) {
	// Blockquote with multiple paragraphs has each paragraph prefixed
	err := htmd.Convert(`<blockquote><p>First paragraph.</p><p>Second paragraph.</p></blockquote>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BlockquoteNested(t *testing.T) {
	// Nested blockquote produces double-prefixed lines
	err := htmd.Convert(`<blockquote><p>Outer quote.</p><blockquote><p>Inner quote.</p></blockquote></blockquote>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BlockquoteSimple(t *testing.T) {
	// Simple blockquote
	err := htmd.Convert(`<blockquote><p>Quote text</p></blockquote>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BlockquoteWithList(t *testing.T) {
	// Blockquote containing a list preserves list items inside quote
	err := htmd.Convert(`<blockquote><p>Quote intro:</p><ul><li>Point one</li><li>Point two</li></ul></blockquote>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BoldAndItalic(t *testing.T) {
	// Nested bold and italic
	err := htmd.Convert(`<p><strong><em>both</em></strong></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BoldStrong(t *testing.T) {
	// Strong tag converts to bold
	err := htmd.Convert(`<p><strong>bold</strong></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_CodeBlock(t *testing.T) {
	// Code block with language preserves content
	err := htmd.Convert(`<pre><code class="language-python">print('hello')</code></pre>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_CodeBlockNoLanguage(t *testing.T) {
	// Code block without a language class preserves content
	err := htmd.Convert(`<pre><code>plain code here</code></pre>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_CodeInlineInParagraph(t *testing.T) {
	// Inline code element nested inside a paragraph
	err := htmd.Convert(`<p>Call the <code>initialize()</code> method first.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_CodeWithBackticksInContent(t *testing.T) {
	// Inline code containing backtick characters is properly escaped
	err := htmd.Convert("<p>Use <code>`backtick` here</code> carefully.</p>", htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EmphasisMarkHighlight(t *testing.T) {
	// mark tag produces highlighted output
	err := htmd.Convert(`<p><mark>highlighted</mark></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EmphasisStrikethroughDel(t *testing.T) {
	// del tag converts to GFM strikethrough
	err := htmd.Convert(`<p><del>deleted text</del></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EmphasisStrikethroughS(t *testing.T) {
	// s tag converts to GFM strikethrough
	err := htmd.Convert(`<p><s>strikethrough</s></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EmphasisSubscript(t *testing.T) {
	// sub tag content is preserved
	err := htmd.Convert(`<p>H<sub>2</sub>O</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EmphasisSuperscript(t *testing.T) {
	// sup tag content is preserved
	err := htmd.Convert(`<p>x<sup>2</sup></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EmphasisUnderlineU(t *testing.T) {
	// u tag content is preserved in output
	err := htmd.Convert(`<p><u>underlined</u></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_FormInputElements(t *testing.T) {
	// Form input elements produce readable output without form mechanics
	err := htmd.Convert(`<form><label for="name">Name:</label><input type="text" id="name" placeholder="Enter name"></form>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_FormSelectOptions(t *testing.T) {
	// Select element with options produces readable output
	err := htmd.Convert(`<form><label>Color:</label><select><option value="red">Red</option><option value="blue" selected>Blue</option><option value="green">Green</option></select></form>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_FormTextarea(t *testing.T) {
	// Textarea element produces readable output
	err := htmd.Convert(`<form><label>Message:</label><textarea>Default text content</textarea></form>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_HeadingH1(t *testing.T) {
	// H1 heading
	err := htmd.Convert(`<h1>Heading 1</h1>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_HeadingH2(t *testing.T) {
	// H2 heading
	err := htmd.Convert(`<h2>Heading 2</h2>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_HeadingH3(t *testing.T) {
	// H3 heading
	err := htmd.Convert(`<h3>Heading 3</h3>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_HeadingH4(t *testing.T) {
	// H4 heading
	err := htmd.Convert(`<h4>Heading 4</h4>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_HeadingH5(t *testing.T) {
	// H5 heading
	err := htmd.Convert(`<h5>Heading 5</h5>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_HeadingH6(t *testing.T) {
	// H6 heading
	err := htmd.Convert(`<h6>Heading 6</h6>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ImageFigureFigcaption(t *testing.T) {
	// Figure with figcaption preserves both image and caption
	err := htmd.Convert(`<figure><img src="sunset.jpg" alt="A sunset"><figcaption>Beautiful sunset over the ocean</figcaption></figure>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ImageLinked(t *testing.T) {
	// Image inside an anchor produces a linked image
	err := htmd.Convert(`<a href="https://example.com"><img src="icon.png" alt="Icon"></a>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ImageNoAlt(t *testing.T) {
	// Image without alt text produces image markdown
	err := htmd.Convert(`<img src="banner.jpg">`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ImageSimple(t *testing.T) {
	// Image with alt text
	err := htmd.Convert(`<img src="photo.jpg" alt="A photo">`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ImageWithTitle(t *testing.T) {
	// Image with title attribute includes title in output
	err := htmd.Convert(`<img src="chart.png" alt="Sales chart" title="Q3 Sales">`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_InlineCode(t *testing.T) {
	// Inline code
	err := htmd.Convert(`<p>Use <code>console.log()</code> to debug</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ItalicEm(t *testing.T) {
	// Em tag converts to italic
	err := htmd.Convert(`<p><em>italic</em></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LineBreakBrTag(t *testing.T) {
	// Single br tag produces a line break in output
	err := htmd.Convert(`<p>First line.<br>Second line.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LineBreakHrTag(t *testing.T) {
	// hr tag produces a horizontal separator between content
	err := htmd.Convert(`<p>Before rule.</p><hr><p>After rule.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LineBreakMultipleBr(t *testing.T) {
	// Multiple consecutive br tags in sequence
	err := htmd.Convert(`<p>Start.<br><br>End.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LinkAnchorFragment(t *testing.T) {
	// Fragment-only anchor link is preserved
	err := htmd.Convert(`<a href="#section">Jump to section</a>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LinkEmptyHref(t *testing.T) {
	// Link with empty href produces output with the link text
	err := htmd.Convert(`<a href="">No destination</a>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LinkImageInside(t *testing.T) {
	// Image inside a link produces a linked image
	err := htmd.Convert(`<a href="https://example.com"><img src="logo.png" alt="Logo"></a>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LinkMailto(t *testing.T) {
	// Mailto link is preserved with mailto: scheme
	err := htmd.Convert(`<a href="mailto:user@example.com">Email us</a>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LinkSimple(t *testing.T) {
	// Simple link
	err := htmd.Convert(`<a href="https://example.com">Example</a>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LinkWithBoldText(t *testing.T) {
	// Link containing bold text preserves formatting
	err := htmd.Convert(`<a href="https://example.com"><strong>Bold link</strong></a>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LinkWithTitle(t *testing.T) {
	// Link with title attribute
	err := htmd.Convert(`<a href="https://example.com" title="Example Site">Example</a>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListDefinitionDl(t *testing.T) {
	// Definition list with dt and dd elements
	err := htmd.Convert(`<dl><dt>Term One</dt><dd>Definition of term one.</dd><dt>Term Two</dt><dd>Definition of term two.</dd></dl>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListItemMultipleParagraphs(t *testing.T) {
	// List item containing multiple paragraphs
	err := htmd.Convert(`<ul><li><p>First paragraph in item.</p><p>Second paragraph in item.</p></li><li>Simple item</li></ul>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListMixedNested(t *testing.T) {
	// Mixed list: ordered list nested inside unordered list
	err := htmd.Convert(`<ul><li>Item A<ol><li>Sub 1</li><li>Sub 2</li></ol></li><li>Item B</li></ul>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListNestedOrdered(t *testing.T) {
	// Nested ordered list with two levels of depth
	err := htmd.Convert(`<ol><li>Step 1<ol><li>Step 1a</li><li>Step 1b</li></ol></li><li>Step 2</li></ol>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListNestedUnordered(t *testing.T) {
	// Nested unordered list with two levels of depth
	err := htmd.Convert(`<ul><li>Parent A<ul><li>Child A1</li><li>Child A2</li></ul></li><li>Parent B</li></ul>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListTaskCheckboxes(t *testing.T) {
	// Task list with checked and unchecked checkboxes
	err := htmd.Convert(`<ul><li><input type="checkbox" checked> Done task</li><li><input type="checkbox"> Pending task</li></ul>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OrderedList(t *testing.T) {
	// Ordered list
	err := htmd.Convert(`<ol><li>First</li><li>Second</li><li>Third</li></ol>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParagraphMultiple(t *testing.T) {
	// Multiple paragraphs are separated by a blank line
	err := htmd.Convert(`<p>First paragraph.</p><p>Second paragraph.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParagraphNestedDivs(t *testing.T) {
	// Text nested inside divs is extracted correctly
	err := htmd.Convert(`<div><div><p>Nested text</p></div></div>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParagraphSimple(t *testing.T) {
	// Simple paragraph converts to plain text
	err := htmd.Convert(`<p>Hello World</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParagraphWithInlineFormatting(t *testing.T) {
	// Paragraph with bold, italic, and a link
	err := htmd.Convert(`<p>This has <strong>bold</strong>, <em>italic</em>, and a <a href="https://example.com">link</a>.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParagraphWithLineBreaks(t *testing.T) {
	// Paragraph with br tags produces line breaks in output
	err := htmd.Convert(`<p>Line one.<br>Line two.<br>Line three.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SemanticAbbr(t *testing.T) {
	// Abbreviation element text is preserved
	err := htmd.Convert(`<p>The <abbr title="World Wide Web">WWW</abbr> is global.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SemanticArticle(t *testing.T) {
	// Article element wrapping content preserves inner content
	err := htmd.Convert(`<article><h2>Article Title</h2><p>Article body.</p></article>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SemanticDefinitionList(t *testing.T) {
	// Definition list with term and description
	err := htmd.Convert(`<dl><dt>HTML</dt><dd>HyperText Markup Language</dd><dt>CSS</dt><dd>Cascading Style Sheets</dd></dl>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SemanticDetailsSummary(t *testing.T) {
	// Details and summary elements produce readable output
	err := htmd.Convert(`<details><summary>Click to expand</summary><p>Hidden content here.</p></details>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SemanticHr(t *testing.T) {
	// Horizontal rule produces a separator in output
	err := htmd.Convert(`<p>Above</p><hr><p>Below</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SemanticMarkHighlight(t *testing.T) {
	// Mark tag produces highlighted output
	err := htmd.Convert(`<p>This is <mark>highlighted text</mark> in a sentence.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SemanticSectionWithHeading(t *testing.T) {
	// Section element with heading preserves structure
	err := htmd.Convert(`<section><h3>Section Heading</h3><p>Section content.</p></section>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SemanticSubSuperscript(t *testing.T) {
	// Subscript and superscript elements are preserved in output
	err := htmd.Convert(`<p>H<sub>2</sub>O and E=mc<sup>2</sup></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SimpleTable(t *testing.T) {
	// Simple table with header
	err := htmd.Convert(`<table><thead><tr><th>Name</th><th>Age</th></tr></thead><tbody><tr><td>Alice</td><td>30</td></tr></tbody></table>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_TableEmpty(t *testing.T) {
	// Empty table produces no output or minimal output
	err := htmd.Convert(`<table></table>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_TableNoThead(t *testing.T) {
	// Table without thead uses first row as implied header
	err := htmd.Convert(`<table><tr><td>Product</td><td>Price</td></tr><tr><td>Apple</td><td>1.00</td></tr></table>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_TablePipeCharsInContent(t *testing.T) {
	// Table cells containing pipe characters are escaped in output
	err := htmd.Convert(`<table><thead><tr><th>Expression</th><th>Result</th></tr></thead><tbody><tr><td>a | b</td><td>true</td></tr></tbody></table>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_TableWithAlignment(t *testing.T) {
	// Table with column alignment attributes
	err := htmd.Convert(`<table><thead><tr><th align="left">Left</th><th align="center">Center</th><th align="right">Right</th></tr></thead><tbody><tr><td>L</td><td>C</td><td>R</td></tr></tbody></table>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_TableWithColspan(t *testing.T) {
	// Table with colspan attribute in a header cell
	err := htmd.Convert(`<table><thead><tr><th colspan="2">Full Name</th></tr></thead><tbody><tr><td>John</td><td>Doe</td></tr></tbody></table>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_UnorderedList(t *testing.T) {
	// Unordered list
	err := htmd.Convert(`<ul><li>Item 1</li><li>Item 2</li><li>Item 3</li></ul>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
