// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a6faf97658e97521e243a9392151afd42f742b88dfb149c44ef65856fa2ca73f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: smoke
package e2e_test

import (
	"strings"
	"testing"

	htmd "github.com/kreuzberg-dev/html-to-markdown/packages/go/v3"
)

func Test_SmokeEmptyString(t *testing.T) {
	// Empty string produces empty output
	err := htmd.Convert(``, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SmokeSimpleHeading(t *testing.T) {
	// H1 heading converts to ATX markdown
	err := htmd.Convert(`<h1>Title</h1>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SmokeSimpleParagraph(t *testing.T) {
	// Simple paragraph converts correctly
	err := htmd.Convert(`<p>Hello World</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
