// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:31f4a2a7c82d9bd8bba3e75556f61a177f25856882f9c76d54108250c0a0c4ac
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/html_to_markdown.h");
}
