// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fcb82ce258d141de81f66a45735d433d79f806c0190b6bc5697ec5414926187f
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/html_to_markdown.h");
}
