// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c294ec384910df9facb6022f30e0dc60b68c21282fb0889995de94406ec70e9a
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/html_to_markdown.h");
}
