# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b404865c05b21c265e1b809a049b2d899b7e6f82a9f58efecfb60fb382714e4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
# Package loaded via library() from CRAN install.

test_dir("tests")
