// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1aa468bb58d7041a551803bf8aaf23fe3ce8a3772b6f8a8df881569c1dcc7c50
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
  },
});
