// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b06e9d6e1c18517f6ae06d622caa5b798eeb1782fc4da4ff85ea30ec7d9759c5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.htmltomarkdown.HtmlToMarkdown;

/** E2e tests for category: smoke. */
class SmokeTest {
    @Test
    void testSmokeEmptyString() throws Exception {
        // Empty string produces empty output
        var result = HtmlToMarkdown.convert("");
        assertEquals("", result.content().orElse("").trim());
    }

    @Test
    void testSmokeSimpleHeading() throws Exception {
        // H1 heading converts to ATX markdown
        var result = HtmlToMarkdown.convert("<h1>Title</h1>");
        assertTrue(result.content().orElse("").contains("# Title"), "expected to contain: " + "# Title");
    }

    @Test
    void testSmokeSimpleParagraph() throws Exception {
        // Simple paragraph converts correctly
        var result = HtmlToMarkdown.convert("<p>Hello World</p>");
        assertEquals("Hello World", result.content().orElse("").trim());
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
    }

}
