// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9f60e38de49cc31c12abbfe777f659ee601e1304b923567e0094fa566bf9703c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const html_to_markdown_rs = @import("html_to_markdown_rs");

// E2e tests for category: smoke

test "smoke_empty_string" {
    // Empty string produces empty output
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("");
    try testing.expectEqual("", result.content);
}

test "smoke_simple_heading" {
    // H1 heading converts to ATX markdown
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<h1>Title</h1>");
    try testing.expect(std.mem.indexOf(u8, result.content, "# Title") != null);
}

test "smoke_simple_paragraph" {
    // Simple paragraph converts correctly
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = html_to_markdown_rs.convert("<p>Hello World</p>");
    try testing.expectEqual("Hello World", result.content);
    try testing.expect(result.content.len > 0);
}
