# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:508777dfdd00fdee2fe74caca07bddd68a7d9eebd03c9d40f88d5fc183f6644c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
devtools::load_all("../../packages/r")

test_dir("tests")
