# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5869b4f023255f78b91382ad2892eadba0bb704ad8580518a79e784bf0537d87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
devtools::load_all("../../packages/r")

test_dir("tests")
