# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d237b6490a28b0bc609810bdd875964e932a2212cab10c0c9e267c6aafb84e8f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
devtools::load_all("../../packages/r")

test_dir("tests")
