# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8acdbccb920f49e984dbfe2de701857e46fc00cf496e7a80a5270a3164af8a43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
