# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:950c548dbe5a1d1ea5ec231fd6d02a2b92e557ab86f2c35a4f934309d548aa9a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.AnnotationKind do
  @moduledoc "The type of an inline text annotation."

  @type t :: term()

  @type bold :: :bold
  @type italic :: :italic
  @type underline :: :underline
  @type strikethrough :: :strikethrough
  @type code :: :code
  @type subscript :: :subscript
  @type superscript :: :superscript
  @type highlight :: :highlight
  @type link :: %{type: :link, url: term(), title: term()}
end
