# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bcce3f9af3eb6e26927f509ab59d8a4c518ba2401b9cb5992210e452ec7ef984
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.AnnotationKind do
  @moduledoc "The type of an inline text annotation."

  @type t :: term()

  @type bold :: :bold
  @type italic :: :italic
  @type underline :: :underline
  @type strikethrough :: :strikethrough
  @type code :: :code
  @type subscript :: :subscript
  @type superscript :: :superscript
  @type highlight :: :highlight
  @type link :: %{type: :link, url: term(), title: term()}
end
