# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:114508407a3d2cef5da4b784cbf79ba761801076ea610693e297ef633a7ea1c8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.CodeBlockStyle do
  @moduledoc "Code block fence style in Markdown output."

  @type t :: :indented | :backticks | :tildes

  @indented :indented
  @backticks :backticks
  @tildes :tildes

  @spec indented() :: t()
  def indented, do: @indented
  @spec backticks() :: t()
  def backticks, do: @backticks
  @spec tildes() :: t()
  def tildes, do: @tildes
end
