# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6290a2033c7627eb6e8972d8617dcad7900e6f4c52887bf73c38e0962666bd6b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.CodeBlockStyle do
  @moduledoc "Code block fence style in Markdown output."

  @type t :: :indented | :backticks | :tildes

  @indented :indented
  @backticks :backticks
  @tildes :tildes

  @spec indented() :: t()
  def indented, do: @indented
  @spec backticks() :: t()
  def backticks, do: @backticks
  @spec tildes() :: t()
  def tildes, do: @tildes
end
