# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9b5026f81c6adf6fd755d6fb035b1088a3709969772ae89d5629d26de6c01a0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentStructure do
  @moduledoc "A structured document tree representing the semantic content of an HTML document."

  defstruct nodes: [],
            source_format: nil
end
