# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed2d0fcb47400e6619cf925499cb7f6758ff8dcb80070dbee319172a20937b7f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  defstruct id: "",
            content: :heading,
            parent: nil,
            children: [],
            annotations: [],
            attributes: nil
end
