# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8471b5ce7bd24c36787a322118c3db0f1a28475870c90036a6e819af935675f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentMetadata do
  @moduledoc "Document-level metadata extracted from `<head>` and top-level elements."

  defstruct title: "",
            description: "",
            keywords: [],
            author: "",
            canonical_url: "",
            base_href: "",
            language: "",
            text_direction: :left_to_right,
            open_graph: %{},
            twitter_card: %{},
            meta_tags: %{}
end
