# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aedbf73b3f25ca71b27e362172507311a427c30565b0f1da9ebca962d5fe510e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentStructure do
  @moduledoc "A structured document tree representing the semantic content of an HTML document."

  defstruct nodes: [],
            source_format: nil
end
