# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e3d9467fcc31f6183927066a34fdd74a8186ada2582db0af36e93f2fd6fec70
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentMetadata do
  @moduledoc "Document-level metadata extracted from `<head>` and top-level elements."

  defstruct title: "",
            description: "",
            keywords: [],
            author: "",
            canonical_url: "",
            base_href: "",
            language: "",
            text_direction: :left_to_right,
            open_graph: %{},
            twitter_card: %{},
            meta_tags: %{}
end
