# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:47ec888f64bb4a49ae85f4885d1e8875d2b5cd1807eda0f5ca146da4e5c3b7a7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  defstruct id: "",
            content: :heading,
            parent: nil,
            children: [],
            annotations: [],
            attributes: nil
end
