# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:965b9aa36e0d51b205cb2c49fb706d05113befd58ca2edbef4b84252608c7fbb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentStructure do
  @moduledoc "A structured document tree representing the semantic content of an HTML document."

  defstruct nodes: [],
            source_format: nil
end
