# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4c6efb1132a7435c5af9f348f760061ba154bd902a9c7e20e70831a188a8fa47
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.DocumentMetadata do
  @moduledoc "Document-level metadata extracted from `<head>` and top-level elements."

  defstruct title: "",
            description: "",
            keywords: [],
            author: "",
            canonical_url: "",
            base_href: "",
            language: "",
            text_direction: :left_to_right,
            open_graph: %{},
            twitter_card: %{},
            meta_tags: %{}
end
