# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c31387a8e23a8977893494e483332b9b10615ecab59d51d354f4a13d0d0165f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.GridCell do
  @moduledoc "A single cell in a table grid."

  defstruct content: "",
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false
end
