# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d7bbfe1f92ccf2c6551643e78e63797e8a71574d7327fe0d3d5a46522a3052a8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.GridCell do
  @moduledoc "A single cell in a table grid."

  defstruct content: "",
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false
end
