# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de20d8f89e9bf6b723b504f2c8a7a9df9033fe575c864ecc37f6d4bebd12f87a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HeadingStyle do
  @moduledoc "Heading style options for Markdown output."

  @type t :: :underlined | :atx | :atx_closed

  @underlined :underlined
  @atx :atx
  @atx_closed :atx_closed

  @spec underlined() :: t()
  def underlined, do: @underlined
  @spec atx() :: t()
  def atx, do: @atx
  @spec atx_closed() :: t()
  def atx_closed, do: @atx_closed
end
