# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1808bc0bf2da644f6add024b1b2907dd7be9f24682a1ad5cb9f853f0133b968e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HeaderMetadata do
  @moduledoc "Header element metadata with hierarchy tracking."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
