# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a0a677fa6473884c909486fa7552cbcd70fe2b2fd62e440e11448af9c1e02c6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HeadingStyle do
  @moduledoc "Heading style options for Markdown output."

  @type t :: :underlined | :atx | :atx_closed

  @underlined :underlined
  @atx :atx
  @atx_closed :atx_closed

  @spec underlined() :: t()
  def underlined, do: @underlined
  @spec atx() :: t()
  def atx, do: @atx
  @spec atx_closed() :: t()
  def atx_closed, do: @atx_closed
end
