# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:32076b1814ffaf8251e0b219ba5c8a4752a083ee1909b9979cf9e3a39646f648
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HeaderMetadata do
  @moduledoc "Header element metadata with hierarchy tracking."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
