# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e6019a01a62364243684d16fc04871082479cb5dedf06bb7341fa0647520807c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HeaderMetadata do
  @moduledoc "Header element metadata with hierarchy tracking."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
