# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d9bcabfb17f156cc1d955ba2f6c4e44a759babe99aa14a9db44d44496b2df971
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HtmlMetadata do
  @moduledoc "Comprehensive metadata extraction result from HTML document."

  defstruct document: nil,
            headers: [],
            links: [],
            images: [],
            structured_data: []
end
