# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a523a404863264a44f4171e38e77e3bf9c8aa5daf94d406e49f148ecabd144ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HtmlMetadata do
  @moduledoc "Comprehensive metadata extraction result from HTML document."

  defstruct document: nil,
            headers: [],
            links: [],
            images: [],
            structured_data: []
end
