# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:50e80ec644e4d1be9ad20294fba83f9e0d9f8d393ef140615cafe631d72b91e7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HtmlMetadata do
  @moduledoc "Comprehensive metadata extraction result from HTML document."

  defstruct document: nil,
            headers: [],
            links: [],
            images: [],
            structured_data: []
end
