# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2d50968166e1aff67b7bc8d485aa51a6a3a247208d0c0051d19aed0da900dd8a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ImageMetadata do
  @moduledoc "Image metadata with source and dimensions."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: %{}
end
