# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b314315b6d1bf0969966efa5e7ce2cbce9c9077698882dfff74e758d8fb6f6ef
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ImageMetadata do
  @moduledoc "Image metadata with source and dimensions."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: %{}
end
