# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76c70f72957e3a21877e3b1fe751904f2d4f49e0ad78f74aa000cf9828a44cf5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ImageMetadata do
  @moduledoc "Image metadata with source and dimensions."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: %{}
end
