# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:452df23c849dad1a2041d6c07cafe149689f7dcc5990475ce36152a3749ac289
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ImageType do
  @moduledoc "Image source classification for proper handling and processing."

  @type t :: :data_uri | :inline_svg | :external | :relative

  @data_uri :data_uri
  @inline_svg :inline_svg
  @external :external
  @relative :relative

  @spec data_uri() :: t()
  def data_uri, do: @data_uri
  @spec inline_svg() :: t()
  def inline_svg, do: @inline_svg
  @spec external() :: t()
  def external, do: @external
  @spec relative() :: t()
  def relative, do: @relative
end
