# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e50b089d9985ad04d32d74664a99186be9d27e234c4ef536ef221279df18d9c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.LinkStyle do
  @moduledoc "Link rendering style in Markdown output."

  @type t :: :inline | :reference

  @inline :inline
  @reference :reference

  @spec inline() :: t()
  def inline, do: @inline
  @spec reference() :: t()
  def reference, do: @reference
end
