# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:597c53452b4553e66cd1a8b5fe68532b0bdce4a09a7014183ce6783bdde5f090
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.LinkStyle do
  @moduledoc "Link rendering style in Markdown output."

  @type t :: :inline | :reference

  @inline :inline
  @reference :reference

  @spec inline() :: t()
  def inline, do: @inline
  @spec reference() :: t()
  def reference, do: @reference
end
