# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:39b719f6cfde93bf5e3d99d77738d9ab19db9dec4c07d822061ac4f2ea5d90ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.LinkType do
  @moduledoc "Link classification based on href value and document context."

  @type t :: :anchor | :internal | :external | :email | :phone | :other

  @anchor :anchor
  @internal :internal
  @external :external
  @email :email
  @phone :phone
  @other :other

  @spec anchor() :: t()
  def anchor, do: @anchor
  @spec internal() :: t()
  def internal, do: @internal
  @spec external() :: t()
  def external, do: @external
  @spec email() :: t()
  def email, do: @email
  @spec phone() :: t()
  def phone, do: @phone
  @spec other() :: t()
  def other, do: @other
end
