# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c3522c32e04152e8797c10aef2157855990b1c9209f5646a5ff2910dc51cfee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.LinkStyle do
  @moduledoc "Link rendering style in Markdown output."

  @type t :: :inline | :reference

  @inline :inline
  @reference :reference

  @spec inline() :: t()
  def inline, do: @inline
  @spec reference() :: t()
  def reference, do: @reference
end
