# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bbbc8a43a140c44de986727d6d9f19ba2792fabeffab5d46b4205186978a0c50
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.LinkMetadata do
  @moduledoc "Hyperlink metadata with categorization and attributes."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: %{}
end
