# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06ab4c22d5262439225a65285f88218606fcae4706eb65b9f32a8d7b01b21c10
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.LinkMetadata do
  @moduledoc "Hyperlink metadata with categorization and attributes."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: %{}
end
