# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a967d5a089d0ac541fdee0573d6431cb87b0e43a85e3c530e0812ccec5e029b8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ListIndentType do
  @moduledoc "List indentation character type."

  @type t :: :spaces | :tabs

  @spaces :spaces
  @tabs :tabs

  @spec spaces() :: t()
  def spaces, do: @spaces
  @spec tabs() :: t()
  def tabs, do: @tabs
end
