# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb278b50ac3982e0ee979b47010ce557a3b2f84946ce7ffe51f7f9a7586090e6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NewlineStyle do
  @moduledoc "Line break syntax in Markdown output."

  @type t :: :spaces | :backslash

  @spaces :spaces
  @backslash :backslash

  @spec spaces() :: t()
  def spaces, do: @spaces
  @spec backslash() :: t()
  def backslash, do: @backslash
end
