# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:46024ae00845323ed50415a7f4f49133c6484d1411f00e342edf6e2c131fae9c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NewlineStyle do
  @moduledoc "Line break syntax in Markdown output."

  @type t :: :spaces | :backslash

  @spaces :spaces
  @backslash :backslash

  @spec spaces() :: t()
  def spaces, do: @spaces
  @spec backslash() :: t()
  def backslash, do: @backslash
end
