# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c6637c3b5e571620479d326af58707dc3f84e6e6f95771ed4f614fe7fb4821bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NewlineStyle do
  @moduledoc "Line break syntax in Markdown output."

  @type t :: :spaces | :backslash

  @spaces :spaces
  @backslash :backslash

  @spec spaces() :: t()
  def spaces, do: @spaces
  @spec backslash() :: t()
  def backslash, do: @backslash
end
