# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aebfa92367922beff940551b2c5fc72cba5b030f2aaae1e9603927e013b2a211
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NodeContext do
  @moduledoc "Context information passed to all visitor methods."

  defstruct node_type: :text,
            tag_name: "",
            attributes: %{},
            depth: 0,
            index_in_parent: 0,
            parent_tag: nil,
            is_inline: false
end
