# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bb5912e3821c6aa99ea4d303cb53535e3ea04f7ca9b29871b2d0499d2efd16b1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NodeContext do
  @moduledoc "Context information passed to all visitor methods."

  defstruct node_type: :text,
            tag_name: "",
            attributes: %{},
            depth: 0,
            index_in_parent: 0,
            parent_tag: nil,
            is_inline: false
end
