# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e06d34db020ca1c7597a2f14602c08238ff68e71b19181cc869786ce1a9e0570
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NodeContext do
  @moduledoc "Context information passed to all visitor methods."

  defstruct node_type: :text,
            tag_name: "",
            attributes: %{},
            depth: 0,
            index_in_parent: 0,
            parent_tag: nil,
            is_inline: false
end
