# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:800075e80f7e902bb3609cc0a595457f8fb8462b4b84fae76d2dc68ed06310fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc "Output format for conversion."

  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @spec markdown() :: t()
  def markdown, do: @markdown
  @spec djot() :: t()
  def djot, do: @djot
  @spec plain() :: t()
  def plain, do: @plain
end
