# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6b8aa623366ff25dc3f5b3d2d8e74e947ec96c5b34464680090832d254ec7a89
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc "Output format for conversion."

  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @spec markdown() :: t()
  def markdown, do: @markdown
  @spec djot() :: t()
  def djot, do: @djot
  @spec plain() :: t()
  def plain, do: @plain
end
