# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d5c9a783c8c873aaeae91a2d91e648c0c2206a67a158565b7e8c4a4a9b6538da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc "Output format for conversion."

  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @spec markdown() :: t()
  def markdown, do: @markdown
  @spec djot() :: t()
  def djot, do: @djot
  @spec plain() :: t()
  def plain, do: @plain
end
