# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1747d7110014766fd764bfe2b14319361885060e0ede05adb9a2cafa25d038c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingOptions do
  @moduledoc "HTML preprocessing options for document cleanup before conversion."

  defstruct enabled: true,
            preset: :standard,
            remove_navigation: true,
            remove_forms: true
end
