# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d763ac8080e1da8e4837dddc1ed092e1478fc96b6dbd6b9a6678114842dd7285
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingOptions do
  @moduledoc "HTML preprocessing options for document cleanup before conversion."

  defstruct enabled: true,
            preset: :standard,
            remove_navigation: true,
            remove_forms: true
end
