# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2418a4a746a006a5c48a2b68e0f275cb1b9c56578adb09e9c8602bccba738aa8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingOptionsUpdate do
  @moduledoc "Partial update for `PreprocessingOptions`."

  defstruct enabled: false,
            preset: :standard,
            remove_navigation: false,
            remove_forms: false
end
