# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:abf24e38523aaee54908502245347ee7e3dc4681440ea90032a501e8dddaa7e1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingOptionsUpdate do
  @moduledoc "Partial update for `PreprocessingOptions`."

  defstruct enabled: false,
            preset: :standard,
            remove_navigation: false,
            remove_forms: false
end
