# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:97974799381ef598aaec3614c3d446229058670234c1e7876650617c6ab22f83
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingPreset do
  @moduledoc "HTML preprocessing aggressiveness level."

  @type t :: :minimal | :standard | :aggressive

  @minimal :minimal
  @standard :standard
  @aggressive :aggressive

  @spec minimal() :: t()
  def minimal, do: @minimal
  @spec standard() :: t()
  def standard, do: @standard
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
end
