# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c8454cf02feefd135494e4cc3252e41454354120308b6ab487a8b77ab79ac98
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingOptions do
  @moduledoc "HTML preprocessing options for document cleanup before conversion."

  defstruct enabled: true,
            preset: :standard,
            remove_navigation: true,
            remove_forms: true
end
