# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8bd6449fc706fcebcd0eb63bef604e119b8841da9acf8b3fecbe5b4a60140fc5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingPreset do
  @moduledoc "HTML preprocessing aggressiveness level."

  @type t :: :minimal | :standard | :aggressive

  @minimal :minimal
  @standard :standard
  @aggressive :aggressive

  @spec minimal() :: t()
  def minimal, do: @minimal
  @spec standard() :: t()
  def standard, do: @standard
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
end
