# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:98beae7ebcbbe003647860da4706dd69a9a8d551ca4295f3aae05ed65fb3c3fd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingOptionsUpdate do
  @moduledoc "Partial update for `PreprocessingOptions`."

  defstruct enabled: false,
            preset: :standard,
            remove_navigation: false,
            remove_forms: false
end
