# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:617020d3a74b359a358eb87880cf8eb9569f4fef97184c0ae3a27173354c7a59
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingPreset do
  @moduledoc "HTML preprocessing aggressiveness level."

  @type t :: :minimal | :standard | :aggressive

  @minimal :minimal
  @standard :standard
  @aggressive :aggressive

  @spec minimal() :: t()
  def minimal, do: @minimal
  @spec standard() :: t()
  def standard, do: @standard
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
end
