# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7ac8e77c71c600e80be55e5bb1ea217ed313740dc649e9575864902333b6019
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ProcessingWarning do
  @moduledoc "A non-fatal warning generated during HTML processing."

  defstruct message: "",
            kind: :image_extraction_failed
end
