# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:71442f4ca9a9aa58c1cf3c61e42d60fe258a0a3426a29de46504287d6774b5b1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ProcessingWarning do
  @moduledoc "A non-fatal warning generated during HTML processing."

  defstruct message: "",
            kind: :image_extraction_failed
end
