# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cccd1a4472eba49d5d97cd20b555fba172547f52743432f93561e5e4253fb5a1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ProcessingWarning do
  @moduledoc "A non-fatal warning generated during HTML processing."

  defstruct message: "",
            kind: :image_extraction_failed
end
