# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:085e561c5626d25eae730dd32aa0e2a0f17dbfabe8b522e9f069a9e5ae134975
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.StructuredData do
  @moduledoc "Structured data block (JSON-LD, Microdata, or RDFa)."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
