# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d95388273a46ad8217d8b8416d1b09936f0865480ba4744f685f4b684f5c3a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.StructuredDataType do
  @moduledoc "Structured data format type."

  @type t :: :json_ld | :microdata | :rd_fa

  @json_ld :json_ld
  @microdata :microdata
  @rd_fa :rd_fa

  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @spec microdata() :: t()
  def microdata, do: @microdata
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
