# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:887575b5b2d611c2f5d6421c3c29c95971e85f33bf72c3a2d6cf119355a8d009
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.StructuredData do
  @moduledoc "Structured data block (JSON-LD, Microdata, or RDFa)."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
