# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d31411b1f88401a186f3b2d8d9a778c555836e0309bc28f6ef4febfc1b64bff4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.StructuredData do
  @moduledoc "Structured data block (JSON-LD, Microdata, or RDFa)."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
