# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f17914220b8ddbdd174e41a9083b40dddeca919ea31fbcedb069cf1d56158e4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TableGrid do
  @moduledoc "A structured table grid with cell-level data including spans."

  defstruct rows: 0,
            cols: 0,
            cells: []
end
