# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7e1199987645dfee0a695880e3c8f836850c242809d15d99d67df53b95d08270
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TableGrid do
  @moduledoc "A structured table grid with cell-level data including spans."

  defstruct rows: 0,
            cols: 0,
            cells: []
end
