# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d45aafc8d6f7354b1f947392700946e7e97be4058695accdc398a50eb0110fc1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  defstruct grid: nil,
            markdown: ""
end
