# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9916a8b3828e3a5a502bd82ea3e31d20dbbdfdde688c7de4e81c19a59b592c98
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  defstruct grid: nil,
            markdown: ""
end
