# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7beabf3f8d73a5bc4ea84c200b7fdc3f2219bacb986af90f598e12e1ba1059ec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  defstruct grid: nil,
            markdown: ""
end
