# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:70904e555158d378e7a2b53b129962f01faa5aec1262ab332f22e1629ce1002c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TableGrid do
  @moduledoc "A structured table grid with cell-level data including spans."

  defstruct rows: 0,
            cols: 0,
            cells: []
end
