# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d7a43612620105e8f203354612dacbc27cbe19222901301be04de76fe62d0777
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TextAnnotation do
  @moduledoc "An inline text annotation with byte-range offsets."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
