# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:477bd0a0facba188f979b6451cfa6dae098761fe2f5676af2fb9c32fa6b13ebc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TextAnnotation do
  @moduledoc "An inline text annotation with byte-range offsets."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
