# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:be65916002f5efe25c09ecc6e4380f7aea35baf0cfc9955e090a4b5193dca5b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TextAnnotation do
  @moduledoc "An inline text annotation with byte-range offsets."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
