# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c167265a8dece5fa2a1e8bbd07e9cf76ddb38e32be4bd64a82306bc8ef373188
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.WhitespaceMode do
  @moduledoc "Whitespace handling strategy during conversion."

  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @spec normalized() :: t()
  def normalized, do: @normalized
  @spec strict() :: t()
  def strict, do: @strict
end
