# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2db63161b4e8771d9f8bbc5e1e3c937a1df6fa0057786bef2cf9e5bd81c41ba4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.WhitespaceMode do
  @moduledoc "Whitespace handling strategy during conversion."

  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @spec normalized() :: t()
  def normalized, do: @normalized
  @spec strict() :: t()
  def strict, do: @strict
end
