# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d6ebc844137b9d240ce4c5afe3dbd80c3f3602c5eebf7e9e45fcca9b09bd0770
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.WhitespaceMode do
  @moduledoc "Whitespace handling strategy during conversion."

  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @spec normalized() :: t()
  def normalized, do: @normalized
  @spec strict() :: t()
  def strict, do: @strict
end
