// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e311fbaf1cb2f59860066311e42edb72f59229eb5e97534c6d8c09356b5e70c5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from 'vitest/config';
import wasm from 'vite-plugin-wasm';
import topLevelAwait from 'vite-plugin-top-level-await';

export default defineConfig({
  plugins: [wasm(), topLevelAwait()],
  test: {
    include: ['tests/**/*.test.ts'],
    globalSetup: './globalSetup.ts',
  },
});
