// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:949f322b9bd9989ff6fbcb84e239b06d82ce75f6e7d3b0154c2571ee4b071241
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    include: ["tests/**/*.test.ts"],
  },
});
