// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4a9e557a9dd712122447fb27f424d041cf1448b0e753620a7b68d6cfc872d4df
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { convert } from '@kreuzberg/html-to-markdown-wasm';

describe('smoke', () => {
  it('smoke_empty_string: Empty string produces empty output', () => {
    const result = convert("");
    expect(result.content.trim()).toBe("");
  });

  it('smoke_simple_heading: H1 heading converts to ATX markdown', () => {
    const result = convert("<h1>Title</h1>");
    expect(result.content).toContain("# Title");
  });

  it('smoke_simple_paragraph: Simple paragraph converts correctly', () => {
    const result = convert("<p>Hello World</p>");
    expect(result.content.trim()).toBe("Hello World");
    expect(result.content.length).toBeGreaterThan(0);
  });
});
