# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de7c621ce0da78b37e21fdb1d38bbbf5c3259509f57cb0f671732eb28b2b7e56
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'html-to-markdown/version'
require_relative 'html-to-markdown/native'

module HtmlToMarkdown
  # Re-export all types and functions from native extension
end
