# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2ddad3a0e4196d0f7824563b5eca866af2d2a475750704444e5ecc0336f8baa6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'html-to-markdown/version'
require_relative 'html-to-markdown/native'

module HtmlToMarkdown
  # Re-export all types and functions from native extension
end
