// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4f88bd3843b6bb501e3b5b5e2e24f16eaa7a173d903ae78dc1d0ad6fcb1c1828
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// The type of an inline text annotation.
///
/// Uses internally tagged representation (`"annotation_type": "bold"`) for JSON serialization.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "annotation_type")]
[JsonDerivedType(typeof(Bold), "bold")]
[JsonDerivedType(typeof(Italic), "italic")]
[JsonDerivedType(typeof(Underline), "underline")]
[JsonDerivedType(typeof(Strikethrough), "strikethrough")]
[JsonDerivedType(typeof(Code), "code")]
[JsonDerivedType(typeof(Subscript), "subscript")]
[JsonDerivedType(typeof(Superscript), "superscript")]
[JsonDerivedType(typeof(Highlight), "highlight")]
[JsonDerivedType(typeof(Link), "link")]
public abstract record AnnotationKind
{
    /// <summary>
    /// Bold / strong emphasis.
    /// </summary>
    public sealed record Bold() : AnnotationKind;

    /// <summary>
    /// Italic / emphasis.
    /// </summary>
    public sealed record Italic() : AnnotationKind;

    /// <summary>
    /// Underline.
    /// </summary>
    public sealed record Underline() : AnnotationKind;

    /// <summary>
    /// Strikethrough / deleted text.
    /// </summary>
    public sealed record Strikethrough() : AnnotationKind;

    /// <summary>
    /// Inline code.
    /// </summary>
    public sealed record Code() : AnnotationKind;

    /// <summary>
    /// Subscript text.
    /// </summary>
    public sealed record Subscript() : AnnotationKind;

    /// <summary>
    /// Superscript text.
    /// </summary>
    public sealed record Superscript() : AnnotationKind;

    /// <summary>
    /// Highlighted / marked text.
    /// </summary>
    public sealed record Highlight() : AnnotationKind;

    /// <summary>
    /// A hyperlink.
    /// </summary>
    public sealed record Link(
        [property: JsonPropertyName("url")] string Url,
        [property: JsonPropertyName("title")] string? Title
    ) : AnnotationKind;

}
