// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:adc3e964c53de018c1d3a8e7e75fb20f13039b845c6831fa0e07b8f10d8cc43d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// The type of an inline text annotation.
///
/// Uses internally tagged representation (`"annotation_type": "bold"`) for JSON serialization.
/// </summary>
    [JsonConverter(typeof(AnnotationKindJsonConverter))]
public abstract record AnnotationKind
{
    /// <summary>
    /// Bold / strong emphasis.
    /// </summary>
    public sealed record Bold() : AnnotationKind;

    /// <summary>
    /// Italic / emphasis.
    /// </summary>
    public sealed record Italic() : AnnotationKind;

    /// <summary>
    /// Underline.
    /// </summary>
    public sealed record Underline() : AnnotationKind;

    /// <summary>
    /// Strikethrough / deleted text.
    /// </summary>
    public sealed record Strikethrough() : AnnotationKind;

    /// <summary>
    /// Inline code.
    /// </summary>
    public sealed record Code() : AnnotationKind;

    /// <summary>
    /// Subscript text.
    /// </summary>
    public sealed record Subscript() : AnnotationKind;

    /// <summary>
    /// Superscript text.
    /// </summary>
    public sealed record Superscript() : AnnotationKind;

    /// <summary>
    /// Highlighted / marked text.
    /// </summary>
    public sealed record Highlight() : AnnotationKind;

    /// <summary>
    /// A hyperlink.
    /// </summary>
    public sealed record Link(
        [property: JsonPropertyName("url")] string Url,
        [property: JsonPropertyName("title")] string? Title
    ) : AnnotationKind;

}

/// <summary>
/// Custom converter for AnnotationKind sealed union with flattened variant fields.
/// </summary>
/// <remarks>
/// Handles JSON objects with a discriminator field (annotation_type) and variant-specific
/// fields at the same level. System.Text.Json's [JsonPolymorphic] cannot handle
/// this layout, so we manually deserialize here.
/// </remarks>
public sealed class AnnotationKindJsonConverter : JsonConverter<AnnotationKind>
{
    public override AnnotationKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException($"Expected JSON object, got {reader.TokenType}");
        }

        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;

        if (!root.TryGetProperty("annotation_type", out var tagElement))
        {
            throw new JsonException($"Missing discriminator field: annotation_type");
        }

        var tagValue = tagElement.GetString();
        if (tagValue == null)
        {
            throw new JsonException("Discriminator field is null");
        }

        // Create a new object wrapping variant fields in a "Value" property
        using var ms = new MemoryStream();
        using var writer = new Utf8JsonWriter(ms);
        writer.WriteStartObject();
        writer.WritePropertyName("Value");
        writer.WriteStartObject();
        foreach (var prop in root.EnumerateObject())
        {
            if (prop.Name != "annotation_type")
            {
                writer.WritePropertyName(prop.Name);
                prop.Value.WriteTo(writer);
            }
        }
        writer.WriteEndObject();
        writer.WriteEndObject();
        writer.Flush();
        ms.Position = 0;

        var variantJson = ms.ToArray();
        return tagValue switch
        {
            "bold" => new AnnotationKind.Bold(),
            "italic" => new AnnotationKind.Italic(),
            "underline" => new AnnotationKind.Underline(),
            "strikethrough" => new AnnotationKind.Strikethrough(),
            "code" => new AnnotationKind.Code(),
            "subscript" => new AnnotationKind.Subscript(),
            "superscript" => new AnnotationKind.Superscript(),
            "highlight" => new AnnotationKind.Highlight(),
            "link" => JsonSerializer.Deserialize<AnnotationKind.Link>(variantJson, options) ?? throw new JsonException("Failed to deserialize variant"),
            _ => throw new JsonException($"Unknown AnnotationKind discriminator: {tagValue}")
        };
    }

    public override void Write(Utf8JsonWriter writer, AnnotationKind value, JsonSerializerOptions options)
    {
        throw new NotSupportedException("AnnotationKind serialization is not supported");
    }
}
