// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bd4df39ed958d898ecc7964b19ba67f16e7c372303fba40b9f12a9ec39e9f6f7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Code block fence style in Markdown output.
///
/// Determines how code blocks (`<pre><code>`) are rendered in Markdown.
/// </summary>
public enum CodeBlockStyle
{
    /// <summary>
    /// Indented code blocks (4 spaces). `CommonMark` standard.
    /// </summary>
    [JsonPropertyName("indented")]
    Indented,
    /// <summary>
    /// Fenced code blocks with backticks (```). Default (GFM). Supports language hints.
    /// </summary>
    [JsonPropertyName("backticks")]
    Backticks,
    /// <summary>
    /// Fenced code blocks with tildes (~~~). Supports language hints.
    /// </summary>
    [JsonPropertyName("tildes")]
    Tildes,
}
