// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1111b9b688f8f4976a17b095e4d56728166e4a4e49c6f27380186966bb9b5e75
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
