// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:35264dc5df4beb8ed6edf6420ee7946043c1411410d0e986ba19d3cc854036f0
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
