// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7cc4dd8dc1d2781f5934fa747e1f6d22b9371f867e2353954bbc87dc0391ba22
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
