// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e6a51f8918c7b0f2736eba00b2a6e1678406c334e1bd3dd3573642e792074991
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : Exception
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
