// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b0429c0028a3c78a2bbf27db59d7967c13a3cc9ce0ef51b7cef1c14e3ae5b167
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Builder for [`ConversionOptions`].
///
/// All fields start with default values. Call `.build()` to produce the final options.
/// </summary>
public sealed class ConversionOptionsBuilder : IDisposable
{
    internal IntPtr Handle { get; }

    internal ConversionOptionsBuilder(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
