// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9bf5112127845d6efbc90261abea31c92b03cf42e71f2b1f3249c5dec6d4c9c0
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
