// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f1e7dfbb40f072dd77ce67724d7f96ff3fb46b397cd111450b9e0e541f905f76
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : Exception
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
