// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:45d472f6f4930033c8486678bf963fdc52fcf26ce67c12b53041b271039702a8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Builder for [`ConversionOptions`].
///
/// All fields start with default values. Call `.build()` to produce the final options.
/// </summary>
public sealed class ConversionOptionsBuilder : IDisposable
{
    internal IntPtr Handle { get; }

    internal ConversionOptionsBuilder(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
