// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7752418fc7c19554339e1af5a113a89d3db57589fdc4a596d3add9766479f345
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Builder for [`ConversionOptions`].
///
/// All fields start with default values. Call `.build()` to produce the final options.
/// </summary>
public sealed class ConversionOptionsBuilder : IDisposable
{
    internal IntPtr Handle { get; }

    internal ConversionOptionsBuilder(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
