// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:135d0c1fc448fd824af6f86a1e9def10c1f05c3d0ed5673d070c99f160b17525
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A single node in the document tree.
/// </summary>
public sealed class DocumentNode
{
    /// <summary>
    /// Deterministic node identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    /// <summary>
    /// The semantic content of this node.
    /// </summary>
    [JsonPropertyName("content")]
    public NodeContent Content { get; set; } = default!;

    /// <summary>
    /// Index of the parent node (None for root nodes).
    /// </summary>
    [JsonPropertyName("parent")]
    public uint? Parent { get; set; } = null;

    /// <summary>
    /// Indices of child nodes in reading order.
    /// </summary>
    [JsonPropertyName("children")]
    public List<uint> Children { get; set; } = [];

    /// <summary>
    /// Inline formatting annotations (bold, italic, links, etc.) with byte offsets into the text.
    /// </summary>
    [JsonPropertyName("annotations")]
    public List<TextAnnotation> Annotations { get; set; } = [];

    /// <summary>
    /// Format-specific attributes (e.g. class, id, data-* attributes).
    /// </summary>
    [JsonPropertyName("attributes")]
    public Dictionary<string, string>? Attributes { get; set; } = null;

}
