// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a03988fb7e45558d7a6adefdf42d75c639228484197c36214d36f905ac0f4ee2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A structured document tree representing the semantic content of an HTML document.
///
/// Uses a flat node array with index-based parent/child references for efficient traversal.
/// </summary>
public sealed class DocumentStructure
{
    /// <summary>
    /// All nodes in document reading order.
    /// </summary>
    [JsonPropertyName("nodes")]
    public List<DocumentNode> Nodes { get; set; } = [];

    /// <summary>
    /// The source format (always "html" for this crate).
    /// </summary>
    [JsonPropertyName("source_format")]
    public string? SourceFormat { get; set; } = null;

}
