// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a7e4008809f6d344c5213f5c859787c3853843e25d83fbbe72a4cd7a39bbb852
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Heading style options for Markdown output.
///
/// Controls how headings (h1-h6) are rendered in the output Markdown.
/// </summary>
public enum HeadingStyle
{
    /// <summary>
    /// Underlined style (=== for h1, --- for h2).
    /// </summary>
    [JsonPropertyName("underlined")]
    Underlined,
    /// <summary>
    /// ATX style (# for h1, ## for h2, etc.). Default.
    /// </summary>
    [JsonPropertyName("atx")]
    Atx,
    /// <summary>
    /// ATX closed style (# title #, with closing hashes).
    /// </summary>
    [JsonPropertyName("atxclosed")]
    AtxClosed,
}
