// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0fb5d67f8086d1e74b0e578e6c6f5acdca88d5254e31c72c7f85fd8c914850ee
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Highlight rendering style for `<mark>` elements.
///
/// Controls how highlighted text is rendered in Markdown output.
/// </summary>
public enum HighlightStyle
{
    /// <summary>
    /// Double equals syntax (==text==). Default. Pandoc-compatible.
    /// </summary>
    [JsonPropertyName("doubleequal")]
    DoubleEqual,
    /// <summary>
    /// Preserve as HTML (==text==). Original HTML tag.
    /// </summary>
    [JsonPropertyName("html")]
    Html,
    /// <summary>
    /// Render as bold (**text**). Uses strong emphasis.
    /// </summary>
    [JsonPropertyName("bold")]
    Bold,
    /// <summary>
    /// Strip formatting, render as plain text. No markup.
    /// </summary>
    [JsonPropertyName("none")]
    None,
}
