// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:18713d8f18afe1b84a0aad9d5daef1edcf2d32687894046e7829963535024b32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }

    public HtmlToMarkdownRsException(string message) : base(message)
    {
        Code = 0;
    }

    public HtmlToMarkdownRsException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
