// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6c38b0078ba64fbbab71c3a77b06e27f38a9b754eb39c1997ec9076963335fe3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }
}
