// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5af377b6b971bbaa89c1b31556d6437c8a85b7991a94a44d251676154aacc208
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }
}
