// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7709a8496060cd94a831978481a294d399344272a981302cf25f953a4e21dabf
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
