// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:00de4ba7cfb1d67ef77407995e2451181228e16b504221374a475a0ac4a0398a
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
