// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b526ab2ea297aa2b56bb48638468c514dfd60ab58673f45d962c062d1b5ba3ec
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
