// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a4aa3a788f7a3dcc78fea08c0632ee7970c71b0dc745e9706c4b0f90e477a38f
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
