// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:343c126772310ddbb79adff62b95c6b1ebe5f29cef4235898ada231b22712074
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
