// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f68bb2296a4cc0809fc84d6c983c4baef1a92fb01a55f913d8f43d1dce8d8ef8
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
