// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:94e5511d9e7e08fb2ac5db269f1d0a5f0ec7a5d5f6a23bf4814906e163d86f29
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Link rendering style in Markdown output.
///
/// Controls whether links and images use inline `[text](url)` syntax or
/// reference-style `[text][1]` syntax with definitions collected at the end.
/// </summary>
public enum LinkStyle
{
    /// <summary>
    /// Inline links: `[text](url)`. Default.
    /// </summary>
    [JsonPropertyName("inline")]
    Inline,
    /// <summary>
    /// Reference-style links: `[text][1]` with `[1]: url` at end of document.
    /// </summary>
    [JsonPropertyName("reference")]
    Reference,
}
