// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8114ec5cda7eb4bb7f9460a5f33bbf46f7d2146ed2c397f1935e546a771a675e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// List indentation character type.
///
/// Controls whether list items are indented with spaces or tabs.
/// </summary>
public enum ListIndentType
{
    /// <summary>
    /// Use spaces for indentation. Default. Width controlled by `list_indent_width`.
    /// </summary>
    [JsonPropertyName("spaces")]
    Spaces,
    /// <summary>
    /// Use tabs for indentation.
    /// </summary>
    [JsonPropertyName("tabs")]
    Tabs,
}
