// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9231f5443048ffc5d8e16d59921fc1ba9e487e738c298d294ecf5b1e045f2a38
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// List indentation character type.
///
/// Controls whether list items are indented with spaces or tabs.
/// </summary>
public enum ListIndentType
{
    /// <summary>
    /// Use spaces for indentation. Default. Width controlled by `list_indent_width`.
    /// </summary>
    [JsonPropertyName("spaces")]
    Spaces,
    /// <summary>
    /// Use tabs for indentation.
    /// </summary>
    [JsonPropertyName("tabs")]
    Tabs,
}
