// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32c8e9ec3f37b1c5c20e3ac6e5fed5e08d3dc357ce5822aa65097ff16eed1bd1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// List indentation character type.
///
/// Controls whether list items are indented with spaces or tabs.
/// </summary>
public enum ListIndentType
{
    /// <summary>
    /// Use spaces for indentation. Default. Width controlled by `list_indent_width`.
    /// </summary>
    [JsonPropertyName("spaces")]
    Spaces,
    /// <summary>
    /// Use tabs for indentation.
    /// </summary>
    [JsonPropertyName("tabs")]
    Tabs,
}
