// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eaab24f98d3153defe42ab146d4caf8fd49b3e75ddb6df3f001ddd154e421637
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Line break syntax in Markdown output.
///
/// Controls how soft line breaks (from `<br>` or line breaks in source) are rendered.
/// </summary>
public enum NewlineStyle
{
    /// <summary>
    /// Two trailing spaces at end of line. Default. Standard Markdown syntax.
    /// </summary>
    [JsonPropertyName("spaces")]
    Spaces,
    /// <summary>
    /// Backslash at end of line. Alternative Markdown syntax.
    /// </summary>
    [JsonPropertyName("backslash")]
    Backslash,
}
