// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:05ece75cb8d81445f9502cbe807c054e0b2d0eabc00f079cc844b0789c046282
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Line break syntax in Markdown output.
///
/// Controls how soft line breaks (from `<br>` or line breaks in source) are rendered.
/// </summary>
public enum NewlineStyle
{
    /// <summary>
    /// Two trailing spaces at end of line. Default. Standard Markdown syntax.
    /// </summary>
    [JsonPropertyName("spaces")]
    Spaces,
    /// <summary>
    /// Backslash at end of line. Alternative Markdown syntax.
    /// </summary>
    [JsonPropertyName("backslash")]
    Backslash,
}
