// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0f30e43c3b9334d650aa8fb395fedf9b957d2d4ee775f0f844280b6efd319a38
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// The semantic content type of a document node.
///
/// Uses internally tagged representation (`"node_type": "heading"`) for JSON serialization.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "node_type")]
[JsonDerivedType(typeof(Heading), "heading")]
[JsonDerivedType(typeof(Paragraph), "paragraph")]
[JsonDerivedType(typeof(List), "list")]
[JsonDerivedType(typeof(ListItem), "list_item")]
[JsonDerivedType(typeof(Table), "table")]
[JsonDerivedType(typeof(Image), "image")]
[JsonDerivedType(typeof(Code), "code")]
[JsonDerivedType(typeof(Quote), "quote")]
[JsonDerivedType(typeof(DefinitionList), "definition_list")]
[JsonDerivedType(typeof(DefinitionItem), "definition_item")]
[JsonDerivedType(typeof(RawBlock), "raw_block")]
[JsonDerivedType(typeof(MetadataBlock), "metadata_block")]
[JsonDerivedType(typeof(Group), "group")]
public abstract record NodeContent
{
    /// <summary>
    /// A heading element (h1-h6).
    /// </summary>
    public sealed record Heading(
        [property: JsonPropertyName("level")] byte Level,
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// A paragraph of text.
    /// </summary>
    public sealed record Paragraph(
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// A list container (ordered or unordered). Children are `ListItem` nodes.
    /// </summary>
    public sealed record List(
        [property: JsonPropertyName("ordered")] bool Ordered
    ) : NodeContent;

    /// <summary>
    /// A single list item.
    /// </summary>
    public sealed record ListItem(
        [property: JsonPropertyName("text")] string Text
    ) : NodeContent;

    /// <summary>
    /// A table with structured cell data.
    /// </summary>
    public sealed record Table(
        [property: JsonPropertyName("grid")] TableGrid Grid
    ) : NodeContent;

    /// <summary>
    /// An image element.
    /// </summary>
    public sealed record Image(
        [property: JsonPropertyName("description")] string? Description,
        [property: JsonPropertyName("src")] string? Src,
        [property: JsonPropertyName("image_index")] uint? ImageIndex
    ) : NodeContent;

    /// <summary>
    /// A code block or inline code.
    /// </summary>
    public sealed record Code(
        [property: JsonPropertyName("text")] string Text,
        [property: JsonPropertyName("language")] string? Language
    ) : NodeContent;

    /// <summary>
    /// A block quote container.
    /// </summary>
    public sealed record Quote() : NodeContent;

    /// <summary>
    /// A definition list container.
    /// </summary>
    public sealed record DefinitionList() : NodeContent;

    /// <summary>
    /// A definition list entry with term and description.
    /// </summary>
    public sealed record DefinitionItem(
        [property: JsonPropertyName("term")] string Term,
        [property: JsonPropertyName("definition")] string Definition
    ) : NodeContent;

    /// <summary>
    /// A raw block preserved as-is (e.g. `<script>`, `<style>` content).
    /// </summary>
    public sealed record RawBlock(
        [property: JsonPropertyName("format")] string Format,
        [property: JsonPropertyName("content")] string Content
    ) : NodeContent;

    /// <summary>
    /// A block of key-value metadata pairs (from `<head>` meta tags).
    /// </summary>
    public sealed record MetadataBlock(
        [property: JsonPropertyName("entries")] global::System.Collections.Generic.List<string> Entries
    ) : NodeContent;

    /// <summary>
    /// A section grouping container (auto-generated from heading hierarchy).
    /// </summary>
    public sealed record Group(
        [property: JsonPropertyName("label")] string? Label,
        [property: JsonPropertyName("heading_level")] byte? HeadingLevel,
        [property: JsonPropertyName("heading_text")] string? HeadingText
    ) : NodeContent;

}
