// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:82d01b977c062fe6fe2dc11e84d1efdc224327b80818fceebd6b40b81bcad43a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>Context passed to every visitor callback.</summary>
public record NodeContext(
    /// <summary>Coarse-grained node type tag.</summary>
    int NodeType,
    /// <summary>HTML element tag name (e.g. "div").</summary>
    string TagName,
    /// <summary>DOM depth (0 = root).</summary>
    ulong Depth,
    /// <summary>0-based sibling index.</summary>
    ulong IndexInParent,
    /// <summary>Parent element tag name, or null at the root.</summary>
    string? ParentTag,
    /// <summary>True when this element is treated as inline.</summary>
    bool IsInline
);
