// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b654c66e152757b515f0d65b8f1f8d01f9d25d5d8fddcda27786b79b35acfeb6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>Context passed to every visitor callback.</summary>
public record NodeContext(
    /// <summary>Coarse-grained node type tag.</summary>
    int NodeType,
    /// <summary>HTML element tag name (e.g. "div").</summary>
    string TagName,
    /// <summary>DOM depth (0 = root).</summary>
    ulong Depth,
    /// <summary>0-based sibling index.</summary>
    ulong IndexInParent,
    /// <summary>Parent element tag name, or null at the root.</summary>
    string? ParentTag,
    /// <summary>True when this element is treated as inline.</summary>
    bool IsInline
);
