// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:af0f00e68d8f17c7a2082d059d82b7bc729f2bf6bd87642851f9fb591d489d29
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
