// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ddceeef0262abf8c317aaf3d2a4151e71155cabd44da81d2d5a1c5edf27dd80b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
