// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:77e6531d28dd7691a5a3876c33c3edb300bdd6f65a3a849935e3236366b13c09
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
