// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3e360088f7d23e0e1516c5df37093fbf3075ea369718bed1e30cf355226a6e01
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException
{
    public PanicException(string message) : base(message) { }

    public PanicException(string message, Exception innerException) : base(message, innerException) { }
}
