// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ab6e4d2ea5a9d76e42b0f59b57fc8ad3ab513285978a5696405ab3a7588d3242
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException
{
    public PanicException(string message) : base(message) { }

    public PanicException(string message, Exception innerException) : base(message, innerException) { }
}
