// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:27c55d0cf549323852d4297feb0d655e8bef178162e42a5fcda60622135ece0b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException
{
    public PanicException(string message) : base(message) { }

    public PanicException(string message, Exception innerException) : base(message, innerException) { }
}
