// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:20ceb9eaf9d40a037a4ca1d399725f6580a50f76e09f947158b5cfa8bf40f956
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
