// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5c827ab26fe05e9dc4be043719ae625cc5b90a044d2f13624ff037907df0338b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
