// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8824576d5468f8c2b2e8c636400f722486465d7dd5d16b601c9f7aacd57067ba
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
