// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9c05dc24241419e2902a93cd483f033b4e6f25c1e26772da7e2f704c0216ab28
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A non-fatal warning generated during HTML processing.
/// </summary>
public sealed class ProcessingWarning
{
    /// <summary>
    /// Human-readable warning message.
    /// </summary>
    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

    /// <summary>
    /// The category of warning.
    /// </summary>
    [JsonPropertyName("kind")]
    public WarningKind Kind { get; set; } = default!;

}
