// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:87fd16a3957c3ed3bc6e20516a598834a1c0e135b6f47ace25ede4d7809cd234
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
