// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:00cdf0cebc7e1f425cc485d3855bb52b5bfa97a08a7213f07a6f503d095546ab
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
