// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ef7bc7d3ec1b62b9f89b46ad4da113fd51ab1a3e82888ef67f85008e3556cd26
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
