// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:897ee111ca9e2ba78d5fe6b99b9d8a9a17ed287fccc4aa987b57618526b4a0a0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A structured table grid with cell-level data including spans.
/// </summary>
public sealed class TableGrid
{
    /// <summary>
    /// Number of rows.
    /// </summary>
    [JsonPropertyName("rows")]
    public uint Rows { get; set; } = 0;

    /// <summary>
    /// Number of columns.
    /// </summary>
    [JsonPropertyName("cols")]
    public uint Cols { get; set; } = 0;

    /// <summary>
    /// All cells in the table (may be fewer than rows*cols due to spans).
    /// </summary>
    [JsonPropertyName("cells")]
    public List<GridCell> Cells { get; set; } = [];

}
