// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:569d53c5c48260a354f629a2300c202a8569df8a1dc85ae78022f1329c1a44bf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// An inline text annotation with byte-range offsets.
///
/// Annotations describe formatting (bold, italic, etc.) and links within a node's text content.
/// </summary>
public sealed class TextAnnotation
{
    /// <summary>
    /// Start byte offset (inclusive) into the parent node's text.
    /// </summary>
    [JsonPropertyName("start")]
    public uint Start { get; set; } = 0;

    /// <summary>
    /// End byte offset (exclusive) into the parent node's text.
    /// </summary>
    [JsonPropertyName("end")]
    public uint End { get; set; } = 0;

    /// <summary>
    /// The type of annotation.
    /// </summary>
    [JsonConverter(typeof(AnnotationKindJsonConverter))]
    [JsonPropertyName("kind")]
    public AnnotationKind Kind { get; set; } = default!;

}
