// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6ccaec0c39ae746641beb4942cfaf8146321552410ee5db149d8c8a8a5618475
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Type alias for a visitor handle (Rc-wrapped `RefCell` for interior mutability).
///
/// This allows visitors to be passed around and shared while still being mutable.
/// </summary>
public sealed class VisitorHandle : IDisposable
{
    internal IntPtr Handle { get; }

    internal VisitorHandle(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
