// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e071ea9e08be5334f2aa005910fc6fb4686b5aa15254cff15191e2626b2ad29e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Categories of processing warnings.
/// </summary>
public enum WarningKind
{
    /// <summary>
    /// An image could not be extracted (e.g. invalid data URI, unsupported format).
    /// </summary>
    [JsonPropertyName("image_extraction_failed")]
    ImageExtractionFailed,
    /// <summary>
    /// The input encoding was not recognized; fell back to UTF-8.
    /// </summary>
    [JsonPropertyName("encoding_fallback")]
    EncodingFallback,
    /// <summary>
    /// The input was truncated due to size limits.
    /// </summary>
    [JsonPropertyName("truncated_input")]
    TruncatedInput,
    /// <summary>
    /// The HTML was malformed but processing continued with best effort.
    /// </summary>
    [JsonPropertyName("malformed_html")]
    MalformedHtml,
    /// <summary>
    /// Sanitization was applied to remove potentially unsafe content.
    /// </summary>
    [JsonPropertyName("sanitization_applied")]
    SanitizationApplied,
    /// <summary>
    /// DOM traversal was truncated because max_depth was exceeded.
    /// </summary>
    [JsonPropertyName("depth_limit_exceeded")]
    DepthLimitExceeded,
}
