// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:37ae3b3823d7b823d9bf899b48fa4cf7fde39e41ed840524f6bb4611cfc7b19b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Categories of processing warnings.
/// </summary>
public enum WarningKind
{
    /// <summary>
    /// An image could not be extracted (e.g. invalid data URI, unsupported format).
    /// </summary>
    [JsonPropertyName("imageextractionfailed")]
    ImageExtractionFailed,
    /// <summary>
    /// The input encoding was not recognized; fell back to UTF-8.
    /// </summary>
    [JsonPropertyName("encodingfallback")]
    EncodingFallback,
    /// <summary>
    /// The input was truncated due to size limits.
    /// </summary>
    [JsonPropertyName("truncatedinput")]
    TruncatedInput,
    /// <summary>
    /// The HTML was malformed but processing continued with best effort.
    /// </summary>
    [JsonPropertyName("malformedhtml")]
    MalformedHtml,
    /// <summary>
    /// Sanitization was applied to remove potentially unsafe content.
    /// </summary>
    [JsonPropertyName("sanitizationapplied")]
    SanitizationApplied,
    /// <summary>
    /// DOM traversal was truncated because max_depth was exceeded.
    /// </summary>
    [JsonPropertyName("depthlimitexceeded")]
    DepthLimitExceeded,
}
