# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7f615d5d38ed67f1fa2bcd66afda487c2c6fe1559df4b57eeb04f750fc05aeb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Exception hierarchy."""


class ConversionError(Exception):
    """Errors that can occur during HTML to Markdown conversion."""


class ParseError(ConversionError):
    """HTML parsing error."""


class SanitizationError(ConversionError):
    """HTML sanitization error."""


class ConfigError(ConversionError):
    """Invalid configuration."""


class IoError(ConversionError):
    """I/O error."""


class PanicError(ConversionError):
    """Panic caught during conversion to prevent unwinding across FFI boundaries."""


class InvalidInputError(ConversionError):
    """Invalid input data."""


class OtherError(ConversionError):
    """Generic conversion error."""
