# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ff731ba218d91be5d96162de5b67082145def3369456b557f46c2a539c9b6836
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Exception hierarchy."""


class ConversionError(Exception):
    """Errors that can occur during HTML to Markdown conversion."""


class ParseError(ConversionError):
    """HTML parsing error."""


class SanitizationError(ConversionError):
    """HTML sanitization error."""


class ConfigError(ConversionError):
    """Invalid configuration."""


class IoError(ConversionError):
    """I/O error."""


class PanicError(ConversionError):
    """Panic caught during conversion to prevent unwinding across FFI boundaries."""


class InvalidInputError(ConversionError):
    """Invalid input data."""


class OtherError(ConversionError):
    """Generic conversion error."""
