# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eabd48002021572f81c43455d66d876b4e65b718883a6c9ff73a930e655ca696
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Exception hierarchy."""


class ConversionError(Exception):
    """Errors that can occur during HTML to Markdown conversion."""


class ParseError(ConversionError):
    """HTML parsing error."""


class SanitizationError(ConversionError):
    """HTML sanitization error."""


class ConfigError(ConversionError):
    """Invalid configuration."""


class IoError(ConversionError):
    """I/O error."""


class PanicError(ConversionError):
    """Panic caught during conversion to prevent unwinding across FFI boundaries."""


class InvalidInputError(ConversionError):
    """Invalid input data."""


class OtherError(ConversionError):
    """Generic conversion error."""
