// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0f2a9ec1da57d37a93c76390d12357f29d18b68a5bf7fe370d71cd9a6762af6b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import html_to_markdown

import gleam/list
import gleam/string

// Empty string produces empty output
pub fn smoke_empty_string_test() {
  let result = html_to_markdown.convert("")
  result |> should.be_ok()
  result.content |> should.equal("")
}

// H1 heading converts to ATX markdown
pub fn smoke_simple_heading_test() {
  let result = html_to_markdown.convert("<h1>Title</h1>")
  result |> should.be_ok()
  result.content |> string.contains("# Title") |> should.equal(True)
}

// Simple paragraph converts correctly
pub fn smoke_simple_paragraph_test() {
  let result = html_to_markdown.convert("<p>Hello World</p>")
  result |> should.be_ok()
  result.content |> should.equal("Hello World")
  result.content |> list.is_empty |> should.equal(False)
}
