# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a841ecc71d153fa0efe5f7aa6ba36d09488e4212ada2aa78bb9fcf75ff83807e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL

#' Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images,
#' and warnings.
#'
#' # Arguments
#'
#' * `html` — the HTML string to convert.
#' * `options` — optional conversion options. Defaults to [`ConversionOptions::default`].
#'   When the `visitor` feature is enabled, a custom [`crate::visitor::HtmlVisitor`] can be
#'   attached via the `visitor` field on `ConversionOptions`.
#'
#' # Example
#'
#' ```
#' use html_to_markdown_rs::convert;
#'
#' let html = "<h1>Hello World</h1>";
#' let result = convert(html, None).unwrap();
#' assert!(result.content.as_deref().unwrap_or("").contains("Hello World"));
#' ```
#'
#' # Errors
#'
#' Returns an error if HTML parsing fails or if the input contains invalid UTF-8.
#' @export
convert <- function(html, options = NULL) {
  .Call("htm_convert", html, options)
}
