# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9c3949a95b65f740a4d042bec1e4ed2eb69b1939160a61fd78e994d14644d95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL
