// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4c1bdb5581c949cdd95b98cdba262513b2992b19b773dec186b015b23280bb2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { convert } from 'html_to_markdown';

describe('smoke', () => {
  it('smoke_empty_string: Empty string produces empty output', () => {
    const result = convert("");
    expect(result.content.trim()).toBe("");
  });

  it('smoke_simple_heading: H1 heading converts to ATX markdown', () => {
    const result = convert("<h1>Title</h1>");
    expect(result.content).toContain("# Title");
  });

  it('smoke_simple_paragraph: Simple paragraph converts correctly', () => {
    const result = convert("<p>Hello World</p>");
    expect(result.content.trim()).toBe("Hello World");
    expect(result.content.length).toBeGreaterThan(0);
  });
});
