// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d014df37cbf2f64b43b21d007fb7b119ad6eec0b9e15880a627715628566a18
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { convert } from 'html_to_markdown';

describe('smoke', () => {
  it('smoke_empty_string: Empty string produces empty output', () => {
    const result = convert("");
    expect(result.content.trim()).toBe("");
  });

  it('smoke_simple_heading: H1 heading converts to ATX markdown', () => {
    const result = convert("<h1>Title</h1>");
    expect(result.content).toContain("# Title");
  });

  it('smoke_simple_paragraph: Simple paragraph converts correctly', () => {
    const result = convert("<p>Hello World</p>");
    expect(result.content.trim()).toBe("Hello World");
    expect(result.content.length).toBeGreaterThan(0);
  });
});
