# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:37f78b7fc0a43b9d90399d2d9154e2cf6cea6136ce812dc92ce5c68939d4b42a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'html_to_markdown'
require 'json'

RSpec.describe 'smoke' do
  it 'smoke_empty_string: Empty string produces empty output' do
    result = HtmlToMarkdown.convert('')
    expect(result.to_s.strip).to eq('')
  end

  it 'smoke_simple_heading: H1 heading converts to ATX markdown' do
    result = HtmlToMarkdown.convert('<h1>Title</h1>')
    expect(result.to_s).to include('# Title')
  end

  it 'smoke_simple_paragraph: Simple paragraph converts correctly' do
    result = HtmlToMarkdown.convert('<p>Hello World</p>')
    expect(result.to_s.strip).to eq('Hello World')
    expect(result.to_s).not_to be_empty
  end
end
