# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c144b8c4875d5d008e8e8a2c6e69d46710aeae789dd8f249477b16d57f04d8d2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'html_to_markdown'
require 'json'

RSpec.describe 'smoke' do
  it 'smoke_empty_string: Empty string produces empty output' do
    result = HtmlToMarkdown.convert('')
    expect(result.strip).to eq('')
  end

  it 'smoke_simple_heading: H1 heading converts to ATX markdown' do
    result = HtmlToMarkdown.convert('<h1>Title</h1>')
    expect(result.to_s).to include('# Title')
  end

  it 'smoke_simple_paragraph: Simple paragraph converts correctly' do
    result = HtmlToMarkdown.convert('<p>Hello World</p>')
    expect(result.strip).to eq('Hello World')
    expect(result).not_to be_empty
  end
end
