# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a1b5f8bf3aba09fa765b4439a7b65ab6d21e0545e2b02cf0416aaf54a7733790
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
