# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fce3aac894dd4a952ead1fa0eb15d4ca6c772bd7fef724352bbb799383af256f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
