// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:710a7a43062f5af26c6551751d81d8de46ce2fa28d5fc8f1c6274f83e9ce25e9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Code block fence style in Markdown output.
 *
 * <p>Determines how code blocks ({@code <pre><code>}) are rendered in Markdown.
 */
public enum CodeBlockStyle {
  /** Indented code blocks (4 spaces). {@code CommonMark} standard. */
  Indented("indented"),
  /**
   * Fenced code blocks with backticks ({@code }{@code ). Default (GFM). Supports language hints.}
   */
  Backticks("backticks"),
  /** Fenced code blocks with tildes (~~~). Supports language hints. */
  Tildes("tildes");

  /** The string value. */
  private final String value;

  CodeBlockStyle(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static CodeBlockStyle fromValue(final String value) {
    for (CodeBlockStyle e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown value: " + value);
  }
}
