// DO NOT EDIT - auto-generated by alef
// alef:hash:9dc756c9d4e18fc379dd710744756a012f2907d94bcf0e6dfd9b3c683ebdb259
package dev.kreuzberg.htmltomarkdown;

/** Invalid configuration. */
public class ConfigErrorException extends ConversionErrorException {
  /** Creates a new ConfigErrorException with the given message. */
  public ConfigErrorException(final String message) {
    super(message);
  }

  /** Creates a new ConfigErrorException with the given message and cause. */
  public ConfigErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
