// DO NOT EDIT - auto-generated by alef
// alef:hash:437b14e116aa0d1db319d8b5eb571aa13fa4204ff8c30f9df054b05e00b8ad76
package dev.kreuzberg.htmltomarkdown;

/**
 * Invalid configuration
 */
public class ConfigErrorException extends ConversionErrorException {
    /** Creates a new ConfigErrorException with the given message. */
    public ConfigErrorException(final String message) {
        super(message);
    }

    /** Creates a new ConfigErrorException with the given message and cause. */
    public ConfigErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
