// DO NOT EDIT - auto-generated by alef
// alef:hash:e2a18baaa893a9f2f714408bad89239d62bdaacee88872db26b5fff14d024e3d
package dev.kreuzberg.htmltomarkdown;

/** Errors that can occur during HTML to Markdown conversion. */
public class ConversionErrorException extends Exception {
  /** Creates a new ConversionErrorException with the given message. */
  public ConversionErrorException(final String message) {
    super(message);
  }

  /** Creates a new ConversionErrorException with the given message and cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
