// DO NOT EDIT - auto-generated by alef
// alef:hash:4553cc3e690250c4ee747f3e121ae20ad80a778b01b0ef6b9e87ef5085f6e6f3
package dev.kreuzberg.htmltomarkdown;

/**
 * Errors that can occur during HTML to Markdown conversion.
 */
public class ConversionErrorException extends Exception {
    /** Creates a new ConversionErrorException with the given message. */
    public ConversionErrorException(final String message) {
        super(message);
    }

    /** Creates a new ConversionErrorException with the given message and cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
