// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:376970bb778d2b11e9b615ea83018a21b507be0ca484df46ccf7fd14f8a0bea8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * The primary result of HTML conversion and extraction.
 *
 * Contains the converted text output, optional structured document tree, metadata, extracted tables, images, and
 * processing warnings.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConversionResultBuilder.class)
public record ConversionResult(
        /** Converted text output (markdown, djot, or plain text). */
        @Nullable String content,
        /** Structured document tree with semantic elements. */
        @Nullable DocumentStructure document,
        /** Extracted HTML metadata (title, OG, links, images, structured data). */
        HtmlMetadata metadata,
        /** Extracted tables with structured cell data and markdown representation. */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<TableData> tables,
        /** Extracted inline images (data URIs and SVGs). */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> images, /** Non-fatal processing warnings. */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<ProcessingWarning> warnings) {
    public static ConversionResultBuilder builder() {
        return new ConversionResultBuilder();
    }
}
