// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2d6dc42f2385be463bcaa71c53f9ef6de2671b3951a4013a6ca442d73c10c26d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A structured document tree representing the semantic content of an HTML document.
 *
 * Uses a flat node array with index-based parent/child references for efficient traversal.
 */
public record DocumentStructure(
        /** All nodes in document reading order. */
        List<DocumentNode> nodes,
        /** The source format (always "html" for this crate). */
        @JsonProperty("source_format") Optional<String> sourceFormat) {
}
