// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f4ebd5ab2ab5b3dfed2b87247eb33d24f5c710ce80904eb7d4551e3342bc0f32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * A single node in the document tree.
 */
public record DocumentNode(
        /** Deterministic node identifier. */
        String id,
        /** The semantic content of this node. */
        NodeContent content,
        /** Index of the parent node (None for root nodes). */
        Optional<Integer> parent,
        /** Indices of child nodes in reading order. */
        List<Integer> children,
        /** Inline formatting annotations (bold, italic, links, etc.) with byte offsets into the text. */
        List<TextAnnotation> annotations,
        /** Format-specific attributes (e.g. class, id, data-* attributes). */
        Optional<Map<String, String>> attributes) {
}
