// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e4d4afcedc18671896bfa4257e97bc181d42cb235ae56620d02424e3432cef8b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Optional;

/**
 * A structured document tree representing the semantic content of an HTML document.
 *
 * <p>Uses a flat node array with index-based parent/child references for efficient traversal.
 */
public record DocumentStructure(
    /** All nodes in document reading order. */
    List<DocumentNode> nodes,
    /** The source format (always "html" for this crate). */
    @JsonProperty("source_format") Optional<String> sourceFormat) {}
