// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d81e80236cd8fdb0d0f605798968049b52c4d21f981edab0f13702dbfef56645
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single cell in a table grid.
 */
public record GridCell(
        /** The text content of the cell. */
        String content,
        /** 0-indexed row position. */
        int row,
        /** 0-indexed column position. */
        int col,
        /** Number of rows this cell spans (default 1). */
        @JsonProperty("row_span") int rowSpan,
        /** Number of columns this cell spans (default 1). */
        @JsonProperty("col_span") int colSpan,
        /** Whether this is a header cell ({@code &lt;th&gt;}). */
        @JsonProperty("is_header") boolean isHeader) {
}
