// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:28ee944253aabb88043a52029de180bcdc689166aba07e092f8f4f186d543ee8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/**
 * Header element metadata with hierarchy tracking.
 *
 * <p>Captures heading elements (h1-h6) with their text content, identifiers, and position in the
 * document structure.
 *
 * <p># Examples
 *
 * <p>{@code }{@code } # use html_to_markdown_rs::metadata::HeaderMetadata; let header =
 * HeaderMetadata { level: 1, text: "Main Title".to_string(), id: Some("main-title".to_string()),
 * depth: 0, html_offset: 145, };
 *
 * <p>assert_eq!(header.level, 1); assert!(header.is_valid()); {@code }{@code }
 */
public record HeaderMetadata(
    /** Header level: 1 (h1) through 6 (h6) */
    byte level,
    /** Normalized text content of the header */
    String text,
    /** HTML id attribute if present */
    Optional<String> id,
    /** Document tree depth at the header element */
    long depth,
    /** Byte offset in original HTML document */
    @JsonProperty("html_offset") long htmlOffset) {}
