// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9c7eeeedd328e579176efd482e20b856e9eaef91ee15182a61d28bbe55ab1bef
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
public class HtmlToMarkdownRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new HtmlToMarkdownRsException. */
    public HtmlToMarkdownRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new HtmlToMarkdownRsException with a cause. */
    public HtmlToMarkdownRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
