// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b0c3e72e1ce07e9c6cde7f81cf10e303c795dcc5215684c1c5cabbcddb03bf4f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

public final class HtmlToMarkdown {
    private HtmlToMarkdown() {
    }

    /**
     * Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images, and warnings.
     *
     * # Arguments
     *
     * * `html` — the HTML string to convert. * `options` — optional conversion options. Defaults to
     * [`ConversionOptions::default`]. When the `visitor` feature is enabled, a custom [`crate::visitor::HtmlVisitor`]
     * can be attached via the `visitor` field on `ConversionOptions`.
     *
     * # Example
     *
     * ``` use html_to_markdown_rs::convert;
     *
     * let html = "
     * <h1>Hello World</h1>"; let result = convert(html, None).unwrap();
     * assert!(result.content.as_deref().unwrap_or("").contains("Hello World")); ```
     *
     * # Errors
     *
     * Returns an error if HTML parsing fails or if the input contains invalid UTF-8.
     */
    public static ConversionResult convert(final String html, final ConversionOptions options)
            throws HtmlToMarkdownRsException {
        java.util.Objects.requireNonNull(html, "html must not be null");
        return HtmlToMarkdownRs.convert(html, options);
    }

    public static ConversionResult convert(final String html) throws HtmlToMarkdownRsException {
        return HtmlToMarkdownRs.convert(html, null);
    }

}
