// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9cdb7f72d07187baf5dbc1d4700775a22426b70c31dcac57b361f04fc54faf7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

public final class HtmlToMarkdown {
    private HtmlToMarkdown() {
    }

    /**
     * Convert HTML to Markdown, returning a ConversionResult with content, metadata, images, and warnings.
     * {@literal @}param html — the HTML string to convert. {@literal @}param options — optional conversion options.
     * Defaults to ConversionOptions::default. {@literal @}throws KreuzbergRsException Returns an error if HTML parsing
     * fails or if the input contains invalid UTF-8.
     */
    public static ConversionResult convert(final String html, final ConversionOptions options)
            throws HtmlToMarkdownRsException {
        java.util.Objects.requireNonNull(html, "html must not be null");
        return HtmlToMarkdownRs.convert(html, options);
    }

    public static ConversionResult convert(final String html) throws HtmlToMarkdownRsException {
        return HtmlToMarkdownRs.convert(html, null);
    }

}
