// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f9346e14266b722fe06948d7db8880bc8f0038e0faeeca39fe4b18f6601e7d4e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image metadata with source and dimensions.
 *
 * Captures {@code &lt;img&gt;} elements and inline {@code &lt;svg&gt;} elements with metadata for image analysis and
 * optimization.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ImageMetadata(
        /** Image source (URL, data URI, or SVG content identifier) */
        String src,
        /** Alternative text from alt attribute (for accessibility) */
        @Nullable String alt,
        /** Title attribute (often shown as tooltip) */
        @Nullable String title,
        /** Image dimensions as (width, height) if available */
        @Nullable List<Integer> dimensions,
        /** Image type classification */
        @JsonProperty("image_type") ImageType imageType,
        /** Additional HTML attributes */
        Map<String, String> attributes) {
}
