// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b360a0f7174f50c2dd2536ef96c0b9daa8d2c8681c2460f21e7026624c2379ba
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Image metadata with source and dimensions.
 *
 * <p>Captures {@code <img>} elements and inline {@code <svg>} elements with metadata for image
 * analysis and optimization.
 *
 * <p># Examples
 *
 * <p>{@code }{@code } # use html_to_markdown_rs::metadata::{ImageMetadata, ImageType}; let img =
 * ImageMetadata { src: "https://example.com/image.jpg".to_string(), alt: Some("An example
 * image".to_string()), title: Some("Example".to_string()), dimensions: Some((800, 600)),
 * image_type: ImageType::External, attributes: Default::default(), };
 *
 * <p>assert_eq!(img.image_type, ImageType::External); {@code }{@code }
 */
public record ImageMetadata(
    /** Image source (URL, data URI, or SVG content identifier) */
    String src,
    /** Alternative text from alt attribute (for accessibility) */
    Optional<String> alt,
    /** Title attribute (often shown as tooltip) */
    Optional<String> title,
    /** Image dimensions as (width, height) if available */
    Optional<List<Integer>> dimensions,
    /** Image type classification */
    @JsonProperty("image_type") ImageType imageType,
    /** Additional HTML attributes */
    Map<String, String> attributes) {}
