// DO NOT EDIT - auto-generated by alef
// alef:hash:e9aa997b77057c398a3e453f0dbf72e4ddc4abf29dffdb5d6d33c0dddcedca4c
package dev.kreuzberg.htmltomarkdown;

/** Invalid input data. */
public class InvalidInputException extends ConversionErrorException {
  /** Creates a new InvalidInputException with the given message. */
  public InvalidInputException(final String message) {
    super(message);
  }

  /** Creates a new InvalidInputException with the given message and cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
