// DO NOT EDIT - auto-generated by alef
// alef:hash:f6b2443d96b0dcb2d85047755574645c6f8927f6b526ed5d67b9081b32ad613d
package dev.kreuzberg.htmltomarkdown;

/**
 * Invalid input data
 */
public class InvalidInputException extends ConversionErrorException {
    /** Creates a new InvalidInputException with the given message. */
    public InvalidInputException(final String message) {
        super(message);
    }

    /** Creates a new InvalidInputException with the given message and cause. */
    public InvalidInputException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
