// DO NOT EDIT - auto-generated by alef
// alef:hash:b78214610edcff961b445671077f59aa778dd5316cf0026c5407d42f71b0c9ff
package dev.kreuzberg.htmltomarkdown;

/** I/O error. */
public class IoErrorException extends ConversionErrorException {
  /** Creates a new IoErrorException with the given message. */
  public IoErrorException(final String message) {
    super(message);
  }

  /** Creates a new IoErrorException with the given message and cause. */
  public IoErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
