// DO NOT EDIT - auto-generated by alef
// alef:hash:d6ee97ea99893b6afc3007e499fb0567df9d50a5b67385842dd5fe99837458d1
package dev.kreuzberg.htmltomarkdown;

/**
 * I/O error
 */
public class IoErrorException extends ConversionErrorException {
    /** Creates a new IoErrorException with the given message. */
    public IoErrorException(final String message) {
        super(message);
    }

    /** Creates a new IoErrorException with the given message and cause. */
    public IoErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
