// DO NOT EDIT - auto-generated by alef
// alef:hash:64eda846e1d2e64dec0ca46902e3d1dda6b700588c438e853ff72285d08e64d3
package dev.kreuzberg.htmltomarkdown;

/**
 * I/O error
 */
public class IoErrorException extends ConversionErrorException {
    /** Creates a new IoErrorException with the given message. */
    public IoErrorException(final String message) {
        super(message);
    }

    /** Creates a new IoErrorException with the given message and cause. */
    public IoErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
