// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a5a6be18721a734a5f7495c5935285301d6384361b6d07ac06304495dd69d5b1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Hyperlink metadata with categorization and attributes.
 *
 * Represents {@code &lt;a&gt;} elements with parsed href values, text content, and link type classification.
 *
 * # Examples
 *
 * {@code }{@code } # use html_to_markdown_rs::metadata::{LinkMetadata, LinkType}; let link = LinkMetadata { href:
 * "https://example.com".to_string(), text: "Example".to_string(), title: Some("Visit Example".to_string()), link_type:
 * LinkType::External, rel: vec!["nofollow".to_string()], attributes: Default::default(), };
 *
 * assert_eq!(link.link_type, LinkType::External); assert_eq!(link.text, "Example"); {@code }{@code }
 */
public record LinkMetadata(
        /** The href URL value */
        String href,
        /** Link text content (normalized, concatenated if mixed with elements) */
        String text,
        /** Optional title attribute (often shown as tooltip) */
        Optional<String> title,
        /** Link type classification */
        @JsonProperty("link_type") LinkType linkType,
        /** Rel attribute values (e.g., "nofollow", "stylesheet", "canonical") */
        List<String> rel,
        /** Additional HTML attributes */
        Map<String, String> attributes) {
}
