// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:80d76d690f03dca481fc3d31ffea3a798f8a2d0bf634defc9991b7b10141193a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * List indentation character type.
 *
 * <p>Controls whether list items are indented with spaces or tabs.
 */
public enum ListIndentType {
  /** Use spaces for indentation. Default. Width controlled by {@code list_indent_width}. */
  Spaces("spaces"),
  /** Use tabs for indentation. */
  Tabs("tabs");

  /** The string value. */
  private final String value;

  ListIndentType(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ListIndentType fromValue(final String value) {
    for (ListIndentType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown value: " + value);
  }
}
