// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b1ecc542c1f56f6b46cf8110f868f3a3894b87643941099bf17ac91586786874
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/** Context passed to every visitor callback. */
public record NodeContext(
    /** Coarse-grained node type tag. */
    int nodeType,
    /** HTML element tag name (e.g. "div"). */
    String tagName,
    /** DOM depth (0 = root). */
    long depth,
    /** 0-based sibling index. */
    long indexInParent,
    /** Parent element tag name, or null at the root. */
    String parentTag,
    /** True when this element is treated as inline. */
    boolean isInline) {}
