// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c28397d87d234ac5c3f23aed93d186a0f2b75f5f8d3bd1a09c73f7e4f0cb1791
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/** Context passed to every visitor callback. */
public record NodeContext(
        /** Coarse-grained node type tag. */
        int nodeType,
        /** HTML element tag name (e.g. "div"). */
        String tagName,
        /** DOM depth (0 = root). */
        long depth,
        /** 0-based sibling index. */
        long indexInParent,
        /** Parent element tag name, or null at the root. */
        String parentTag,
        /** True when this element is treated as inline. */
        boolean isInline) {
}
