// DO NOT EDIT - auto-generated by alef
// alef:hash:58e11447fc62a95b17748d623f83998fd1dadeae6c69dfcf435859f0eeec775a
package dev.kreuzberg.htmltomarkdown;

/** Generic conversion error. */
public class OtherException extends ConversionErrorException {
  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
