// DO NOT EDIT - auto-generated by alef
// alef:hash:82ce8650a740871ca52e7cc90ab3687d58dd3943f02d0d731ae582293238e124
package dev.kreuzberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
