// DO NOT EDIT - auto-generated by alef
// alef:hash:f0430ba787a0df06567dcb729f18498554d70f7ba21a9706a2affdbd8c4fad12
package dev.kreuzberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
