// DO NOT EDIT - auto-generated by alef
// alef:hash:7c1a2d00ad0ad654fff57e9a7959128182974eca6358ac1ac2e799f4fbb6fc2e
package dev.kreuzberg.htmltomarkdown;

/**
 * Panic caught during conversion to prevent unwinding across FFI boundaries
 */
public class PanicException extends ConversionErrorException {
    /** Creates a new PanicException with the given message. */
    public PanicException(final String message) {
        super(message);
    }

    /** Creates a new PanicException with the given message and cause. */
    public PanicException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
