// DO NOT EDIT - auto-generated by alef
// alef:hash:e2a9f208e74f2c7f85f15c1d163fdb6d8cc4e51eed4b93ff179043d1266334c0
package dev.kreuzberg.htmltomarkdown;

/** Panic caught during conversion to prevent unwinding across FFI boundaries. */
public class PanicException extends ConversionErrorException {
  /** Creates a new PanicException with the given message. */
  public PanicException(final String message) {
    super(message);
  }

  /** Creates a new PanicException with the given message and cause. */
  public PanicException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
