// DO NOT EDIT - auto-generated by alef
// alef:hash:58261eaa00a8e25897fddcf412bffdd64e51cd1f106a7ba2765a8e3492ecacf7
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML parsing error
 */
public class ParseErrorException extends ConversionErrorException {
    /** Creates a new ParseErrorException with the given message. */
    public ParseErrorException(final String message) {
        super(message);
    }

    /** Creates a new ParseErrorException with the given message and cause. */
    public ParseErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
