// DO NOT EDIT - auto-generated by alef
// alef:hash:a82c4324407c4112999d9c7822dd26b97926132213d604c4c47311d65c54bef5
package dev.kreuzberg.htmltomarkdown;

/** HTML parsing error. */
public class ParseErrorException extends ConversionErrorException {
  /** Creates a new ParseErrorException with the given message. */
  public ParseErrorException(final String message) {
    super(message);
  }

  /** Creates a new ParseErrorException with the given message and cause. */
  public ParseErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
