// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d12941ece905d9af6922d14c733545ab5a3aa70884ef3973db24fa1f4754cf60
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * HTML preprocessing options for document cleanup before conversion.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class PreprocessingOptionsBuilder {

    private boolean enabled = true;
    private PreprocessingPreset preset = null;
    private boolean removeNavigation = true;
    private boolean removeForms = true;

    /** Sets the enabled field. */
    public PreprocessingOptionsBuilder withEnabled(final boolean value) {
        this.enabled = value;
        return this;
    }

    /** Sets the preset field. */
    public PreprocessingOptionsBuilder withPreset(final PreprocessingPreset value) {
        this.preset = value;
        return this;
    }

    /** Sets the removeNavigation field. */
    public PreprocessingOptionsBuilder withRemoveNavigation(final boolean value) {
        this.removeNavigation = value;
        return this;
    }

    /** Sets the removeForms field. */
    public PreprocessingOptionsBuilder withRemoveForms(final boolean value) {
        this.removeForms = value;
        return this;
    }

    /** Builds the PreprocessingOptions instance. */
    public PreprocessingOptions build() {
        return new PreprocessingOptions(enabled, preset, removeNavigation, removeForms);
    }
}
