// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1891cb424f425e90a044f89df24a70768b80c9524d496c45d6a8c194303326e8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;

/** HTML preprocessing options for document cleanup before conversion. */
public record PreprocessingOptions(
    /** Enable HTML preprocessing globally */
    boolean enabled,
    /** Preprocessing preset level (Minimal, Standard, Aggressive) */
    PreprocessingPreset preset,
    /** Remove navigation elements (nav, breadcrumbs, menus, sidebars) */
    @JsonProperty("remove_navigation") boolean removeNavigation,
    /** Remove form elements (forms, inputs, buttons, etc.) */
    @JsonProperty("remove_forms") boolean removeForms) {
  public static PreprocessingOptionsBuilder builder() {
    return new PreprocessingOptionsBuilder();
  }
}
