// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32fcfe5c7abaa182ff2ba9f5109d86f06e6d171713343c0a41780be37fee15af
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * HTML preprocessing options for document cleanup before conversion.
 */
public record PreprocessingOptions(
        /** Enable HTML preprocessing globally */
        boolean enabled,
        /** Preprocessing preset level (Minimal, Standard, Aggressive) */
        PreprocessingPreset preset,
        /** Remove navigation elements (nav, breadcrumbs, menus, sidebars) */
        @JsonProperty("remove_navigation") boolean removeNavigation,
        /** Remove form elements (forms, inputs, buttons, etc.) */
        @JsonProperty("remove_forms") boolean removeForms) {
    public static PreprocessingOptionsBuilder builder() {
        return new PreprocessingOptionsBuilder();
    }
}
