// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:78dd7c41cc091cb624eca277f973be8ab63880e4454d46174f612219b48d89b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.Optional;

/**
 * Partial update for {@code PreprocessingOptions}.
 *
 * <p>This struct uses {@code Option<T>} to represent optional fields that can be selectively
 * updated. Only specified fields (Some values) will override existing options; None values leave
 * the corresponding fields unchanged when applied via [{@code PreprocessingOptions::apply_update}].
 */
public class PreprocessingOptionsUpdateBuilder {

  private Optional<Boolean> enabled = Optional.empty();
  private Optional<PreprocessingPreset> preset = Optional.empty();
  private Optional<Boolean> removeNavigation = Optional.empty();
  private Optional<Boolean> removeForms = Optional.empty();

  /** Sets the enabled field. */
  public PreprocessingOptionsUpdateBuilder withEnabled(final Optional<Boolean> value) {
    this.enabled = value;
    return this;
  }

  /** Sets the preset field. */
  public PreprocessingOptionsUpdateBuilder withPreset(final Optional<PreprocessingPreset> value) {
    this.preset = value;
    return this;
  }

  /** Sets the removeNavigation field. */
  public PreprocessingOptionsUpdateBuilder withRemoveNavigation(final Optional<Boolean> value) {
    this.removeNavigation = value;
    return this;
  }

  /** Sets the removeForms field. */
  public PreprocessingOptionsUpdateBuilder withRemoveForms(final Optional<Boolean> value) {
    this.removeForms = value;
    return this;
  }

  /** Builds the PreprocessingOptionsUpdate instance. */
  public PreprocessingOptionsUpdate build() {
    return new PreprocessingOptionsUpdate(enabled, preset, removeNavigation, removeForms);
  }
}
