// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:315bbf839b0fa15e25a9f4b47fd442c07de5559c96467c794e07224bbf95119e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/**
 * A non-fatal warning generated during HTML processing.
 */
public record ProcessingWarning(String message, WarningKind kind) {
}
