// DO NOT EDIT - auto-generated by alef
// alef:hash:85c6ccdc05b38ce9d2f3df8841cc2bf0aff16438d40797f95e0a97d0fdf20c36
package dev.kreuzberg.htmltomarkdown;

/** HTML sanitization error. */
public class SanitizationErrorException extends ConversionErrorException {
  /** Creates a new SanitizationErrorException with the given message. */
  public SanitizationErrorException(final String message) {
    super(message);
  }

  /** Creates a new SanitizationErrorException with the given message and cause. */
  public SanitizationErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
