// DO NOT EDIT - auto-generated by alef
// alef:hash:e1aebb708e223e1992590989e695e33f5e7adf29577ff76b4823a1bba289cc6e
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
    /** Creates a new SanitizationErrorException with the given message. */
    public SanitizationErrorException(final String message) {
        super(message);
    }

    /** Creates a new SanitizationErrorException with the given message and cause. */
    public SanitizationErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
