// DO NOT EDIT - auto-generated by alef
// alef:hash:63ee354a226312762cea3045effd410741dae65f72da851a06ed4a0dc51e8108
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
    /** Creates a new SanitizationErrorException with the given message. */
    public SanitizationErrorException(final String message) {
        super(message);
    }

    /** Creates a new SanitizationErrorException with the given message and cause. */
    public SanitizationErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
