// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d57c5747c34f5d277118f2c68ee4509eb10150196c9075bfff3d179cbb52fabc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/**
 * Structured data block (JSON-LD, Microdata, or RDFa).
 *
 * <p>Represents machine-readable structured data found in the document. JSON-LD blocks are
 * collected as raw JSON strings for flexibility.
 *
 * <p># Examples
 *
 * <p>{@code }{@code } # use html_to_markdown_rs::metadata::{StructuredData, StructuredDataType};
 * let schema = StructuredData { data_type: StructuredDataType::JsonLd, raw_json:
 * r#"{"{@literal @}context":"https://schema.org","{@literal @}type":"Article"}"#.to_string(),
 * schema_type: Some("Article".to_string()), };
 *
 * <p>assert_eq!(schema.data_type, StructuredDataType::JsonLd); {@code }{@code }
 */
public record StructuredData(
    /** Type of structured data (JSON-LD, Microdata, RDFa) */
    @JsonProperty("data_type") StructuredDataType dataType,
    /** Raw JSON string (for JSON-LD) or serialized representation */
    @JsonProperty("raw_json") String rawJson,
    /** Schema type if detectable (e.g., "Article", "Event", "Product") */
    @JsonProperty("schema_type") Optional<String> schemaType) {}
