// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c2233122e05869c33bf775b67c0e51e2d9aa98a7769ff0661157a9cf1ead3e62
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/** A top-level extracted table with both structured data and markdown representation. */
public record TableData(TableGrid grid, String markdown) {}
