// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:85f8eca83e724fa79fa1c8ba62fdbed6a4e82668ffd6e2eb477896258c360abc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * A structured table grid with cell-level data including spans.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TableGridBuilder.class)
public record TableGrid(
        /** Number of rows. */
        int rows,
        /** Number of columns. */
        int cols, /** All cells in the table (may be fewer than rows*cols due to spans). */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<GridCell> cells) {
    public static TableGridBuilder builder() {
        return new TableGridBuilder();
    }
}
