// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7fe8c445c5ef2f1e660a45feff0c8f9602f0737b7e1920f785c5aae5f3ffa52c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;

/** A structured table grid with cell-level data including spans. */
public class TableGridBuilder {

  private int rows = 0;
  private int cols = 0;
  private List<GridCell> cells = List.of();

  /** Sets the rows field. */
  public TableGridBuilder withRows(final int value) {
    this.rows = value;
    return this;
  }

  /** Sets the cols field. */
  public TableGridBuilder withCols(final int value) {
    this.cols = value;
    return this;
  }

  /** Sets the cells field. */
  public TableGridBuilder withCells(final List<GridCell> value) {
    this.cells = value;
    return this;
  }

  /** Builds the TableGrid instance. */
  public TableGrid build() {
    return new TableGrid(rows, cols, cells);
  }
}
