// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e98b859242c13143e75f7ca84d13377856d01b0e8501920757b1041604015ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;

/** A structured table grid with cell-level data including spans. */
public record TableGrid(int rows, int cols, List<GridCell> cells) {
  public static TableGridBuilder builder() {
    return new TableGridBuilder();
  }
}
