// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f12cefbf50d6a380e5ff4d289fd7ea4d4402f6cda309a3687ccfb7a5cc842998
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/**
 * A top-level extracted table with both structured data and markdown representation.
 */
public record TableData(TableGrid grid, String markdown) {
}
