// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:183f404a904f629d365a727e9113837eb8ff4acd5f7f5e56d8de6333d82c20f3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/**
 * An inline text annotation with byte-range offsets.
 *
 * Annotations describe formatting (bold, italic, etc.) and links within a node's text content.
 */
public record TextAnnotation(int start, int end, AnnotationKind kind) {
}
