// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9364961b86a3a281a91cd30bdfa71147482a1565d69b66f361c9cbcc204d74e0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

/**
 * An inline text annotation with byte-range offsets.
 *
 * <p>Annotations describe formatting (bold, italic, etc.) and links within a node's text content.
 */
public record TextAnnotation(int start, int end, AnnotationKind kind) {}
