// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6097790a5145193725fe1f30fe306dc53d4596829f2898766c53d8edf09b8b10
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:html_to_markdown_rs/html_to_markdown_rs.dart';

// E2e tests for category: smoke
void main() {
  test('Empty string produces empty output', () {
    final result = convert('');
    expect(result.content.trim(), equals(''));
  });

  test('H1 heading converts to ATX markdown', () {
    final result = convert('<h1>Title</h1>');
    expect(result.content, contains('# Title'));
  });

  test('Simple paragraph converts correctly', () {
    final result = convert('<p>Hello World</p>');
    expect(result.content.trim(), equals('Hello World'));
    expect(result.content, isNotEmpty);
  });

}
