// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:180273e4f7b931414b02e07c9335dd5f841afcfb8a7a20c3fc8f89b21bb7959b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: edge-cases
package e2e_test

import (
	"strings"
	"testing"

	htmd "github.com/kreuzberg-dev/html-to-markdown/packages/go/v3"
)

type testVisitorVisitorCustomElementWithNesting struct{}

func (v *testVisitorVisitorCustomElementWithNesting) VisitCustomElement(_ htmd.NodeContext, tagName, html string) htmd.VisitResult {
	return htmd.VisitResultCustom(`[CUSTOM WIDGET]`)
}

type testVisitorVisitorDeeplyNestedSkip struct{}

func (v *testVisitorVisitorDeeplyNestedSkip) VisitMark(_ htmd.NodeContext, text string) htmd.VisitResult {
	return htmd.VisitResultSkip
}

type testVisitorVisitorElementEndModification struct{}

func (v *testVisitorVisitorElementEndModification) VisitElementEnd(_ htmd.NodeContext, output string) htmd.VisitResult {
	return htmd.VisitResultCustom(`MODIFIED OUTPUT`)
}

type testVisitorVisitorElementStartSkipEntireSubtree struct{}

func (v *testVisitorVisitorElementStartSkipEntireSubtree) VisitElementStart(_ htmd.NodeContext) htmd.VisitResult {
	return htmd.VisitResultSkip
}

type testVisitorVisitorUnknownTagPreservation struct{}

func (v *testVisitorVisitorUnknownTagPreservation) VisitCustomElement(_ htmd.NodeContext, tagName, html string) htmd.VisitResult {
	return htmd.VisitResultPreserveHtml
}

func Test_EmptyHtml(t *testing.T) {
	// Empty HTML document
	err := htmd.Convert(`<html><head></head><body></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EncodingCjkCharacters(t *testing.T) {
	// CJK (Chinese, Japanese, Korean) characters are preserved
	err := htmd.Convert(`<p>中文内容</p><p>日本語テキスト</p><p>한국어 텍스트</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EncodingHtmlEntities(t *testing.T) {
	// Common HTML entities are decoded in output
	err := htmd.Convert(`<p>&amp; &lt; &gt; &nbsp; &quot; &apos;</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EncodingNamedEntities(t *testing.T) {
	// Named HTML entities like &mdash; and &hellip; are decoded
	err := htmd.Convert(`<p>Em dash&mdash;used for parenthetical remarks&mdash;is common. Ellipsis&hellip; indicates omission. Non-breaking&nbsp;space.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EncodingNumericEntities(t *testing.T) {
	// Numeric HTML entities (decimal and hex) are decoded
	err := htmd.Convert(`<p>Copyright: &#169; Trade: &#174; Euro: &#8364; Hex: &#x00A9;</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EncodingUnicodeEmoji(t *testing.T) {
	// Emoji and Unicode characters are preserved
	err := htmd.Convert(`<p>Hello 🌍 World 🚀</p><p>Stars: ⭐ ✨</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_HtmlCommentsOnly(t *testing.T) {
	// Document containing only HTML comments produces empty output
	err := htmd.Convert(`<!-- This is a comment --><!-- Another comment -->`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_JustWhitespaceInput(t *testing.T) {
	// Input that is only whitespace characters (spaces, tabs, newlines) produces empty output
	err := htmd.Convert(`   `, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MalformedDeeplyNestedElements(t *testing.T) {
	// Deeply nested elements (100 levels) are handled without stack overflow
	err := htmd.Convert(`<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><p>Deeply nested content</p></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MalformedMissingBlockClosingTags(t *testing.T) {
	// Missing closing tags on block elements are auto-closed by parser
	err := htmd.Convert(`<div><h1>Title<p>First paragraph<p>Second paragraph</div>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MalformedOverlappingTags(t *testing.T) {
	// Overlapping bold/italic tags are recovered by the HTML parser without panic
	err := htmd.Convert(`<p><b><i>bold and italic</b></i></p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MalformedUnclosedParagraph(t *testing.T) {
	// Unclosed <p> tag is recovered gracefully and content is preserved
	err := htmd.Convert(`<p>This paragraph is never closed`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ScriptTagsOnly(t *testing.T) {
	// Document with only script tags produces empty output (scripts are stripped)
	err := htmd.Convert(`<html><head><script>alert('xss')</script></head><body><script>document.write('hello')</script></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StyleTagsOnly(t *testing.T) {
	// Document with only style tags produces empty output (styles are stripped)
	err := htmd.Convert(`<html><head><style>body { color: red; }</style></head><body><style>.foo { margin: 0; }</style></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_VisitorCustomElementWithNesting(t *testing.T) {
	// Visitor handles custom elements with nested content
	visitor := &testVisitorVisitorCustomElementWithNesting{}
	err := htmd.Convert(`<div><custom-widget data-value="123"><p>Widget content here</p><span>With nested elements</span></custom-widget></div>`, htmd.ConversionOptions{}, visitor)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_VisitorDeeplyNestedSkip(t *testing.T) {
	// Visitor skips deeply nested elements
	visitor := &testVisitorVisitorDeeplyNestedSkip{}
	err := htmd.Convert(`<div><p>Outer <em>emphasis <strong>with bold <mark>and highlight</mark></strong></em> text</p></div>`, htmd.ConversionOptions{}, visitor)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_VisitorElementEndModification(t *testing.T) {
	// Visitor modifies element at end after children processed
	visitor := &testVisitorVisitorElementEndModification{}
	err := htmd.Convert(`<blockquote><p>Original quote</p></blockquote>`, htmd.ConversionOptions{}, visitor)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_VisitorElementStartSkipEntireSubtree(t *testing.T) {
	// Visitor skips at element_start level removes entire subtree
	visitor := &testVisitorVisitorElementStartSkipEntireSubtree{}
	err := htmd.Convert(`<div><h1>Title</h1><p>Content</p></div>`, htmd.ConversionOptions{}, visitor)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_VisitorUnknownTagPreservation(t *testing.T) {
	// Visitor preserves unknown HTML tags as raw HTML
	visitor := &testVisitorVisitorUnknownTagPreservation{}
	err := htmd.Convert(`<article><p>Article text</p><x-custom>Custom element with content</x-custom><p>More article text</p></article>`, htmd.ConversionOptions{}, visitor)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_WhitespaceOnly(t *testing.T) {
	// Whitespace-only content
	err := htmd.Convert(`<p>   </p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_XssOnclickHandlerRemoved(t *testing.T) {
	// onclick and other on* event handlers are removed from elements
	err := htmd.Convert(`<p><a href="https://example.com" onclick="alert('xss')">Click me</a></p><button onmouseover="steal_data()">Hover me</button>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_XssScriptTagStripped(t *testing.T) {
	// Script tag content is stripped and does not appear in output
	err := htmd.Convert(`<p>Safe content.</p><script>alert('xss')</script><p>More safe content.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_XssSvgNestedScriptStripped(t *testing.T) {
	// Script tags nested inside SVG are stripped
	err := htmd.Convert(`<p>Before SVG.</p><svg xmlns="http://www.w3.org/2000/svg"><script>alert('svg-xss')</script><text>SVG text</text></svg><p>After SVG.</p>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
