// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f3017b91dc86422add3c3eca200aa6dd9aff02c073b66f771fbbca769a3815e0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: metadata
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	htmd "github.com/kreuzberg-dev/html-to-markdown/packages/go/v3"
)

func Test_MetadataAuthorMeta(t *testing.T) {
	// Extract author from <meta name='author'> tag
	err := htmd.Convert(`<html><head><title>Page</title><meta name="author" content="Jane Doe"></head><body><p>Content</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataCanonicalUrl(t *testing.T) {
	// Extract canonical URL from <link rel='canonical'> tag
	err := htmd.Convert(`<html><head><title>Page</title><link rel="canonical" href="https://example.com/canonical-page"></head><body><p>Content</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataDescriptionMeta(t *testing.T) {
	// Extract description from <meta name='description'> tag
	err := htmd.Convert(`<html><head><title>Page</title><meta name="description" content="This is the page description."></head><body><p>Content</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataDublinCore(t *testing.T) {
	// Extract Dublin Core metadata tags
	err := htmd.Convert(`<html><head><title>Scholarly Work</title><meta name="DC.title" content="Principles of Knowledge Management"><meta name="DC.creator" content="Dr. Alice Johnson"><meta name="DC.date" content="2023-06-15"><meta name="DC.subject" content="Knowledge Management"><meta name="DC.publisher" content="Academic Press"></head><body><p>This is a scholarly article.</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataExtractAllImages(t *testing.T) {
	// Extract all images from a document into metadata
	err := htmd.Convert(`<html><head><title>Gallery</title></head><body><img src="https://example.com/photo1.jpg" alt="Photo 1"><img src="https://example.com/photo2.png" alt="Photo 2"><img src="/local/image.webp" alt="Local image"></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataExtractAllLinks(t *testing.T) {
	// Extract all links from a document into metadata
	err := htmd.Convert(`<html><head><title>Links Page</title></head><body><p>Visit <a href="https://example.com">Example</a> or <a href="https://docs.example.com">Docs</a>.</p><p>Also see <a href="/relative/path">relative link</a> and <a href="mailto:hello@example.com">email us</a>.</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataHeadersHierarchy(t *testing.T) {
	// Extract heading hierarchy from document into metadata
	err := htmd.Convert(`<html><head><title>Docs</title></head><body><h1>Introduction</h1><h2>Getting Started</h2><h3>Installation</h3><h3>Configuration</h3><h2>Advanced Usage</h2><h3>Custom Options</h3></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataKeywordsMeta(t *testing.T) {
	// Extract keywords from <meta name='keywords'> tag
	err := htmd.Convert(`<html><head><title>Page</title><meta name="keywords" content="rust, markdown, html, converter"></head><body><p>Content</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataLangAttribute(t *testing.T) {
	// Extract language from html lang attribute
	err := htmd.Convert(`<html lang="es"><head><title>Spanish Page</title></head><body><h1>Hola Mundo</h1><p>Este es un documento en español.</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataMicrodataSchemaArticle(t *testing.T) {
	// Extract schema.org microdata for Article
	err := htmd.Convert(`<html><head><title>Article</title></head><body><article itemscope itemtype="https://schema.org/Article"><h1 itemprop="headline">Breaking News Today</h1><span itemprop="author">Jane Reporter</span><span itemprop="datePublished">2024-04-22</span><div itemprop="articleBody"><p>The article content goes here with important information about the breaking news story.</p></div></article></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataMicrodataSchemaBreadcrumb(t *testing.T) {
	// Extract schema.org breadcrumb navigation microdata
	err := htmd.Convert(`<html><head><title>Navigation</title></head><body><nav itemscope itemtype="https://schema.org/BreadcrumbList"><span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a itemprop="item" href="https://example.com"><span itemprop="name">Home</span></a></span><span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a itemprop="item" href="https://example.com/products"><span itemprop="name">Products</span></a></span><span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><span itemprop="name">Current Page</span></span></nav></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataMicrodataSchemaOrganization(t *testing.T) {
	// Extract schema.org microdata for Organization
	err := htmd.Convert(`<html><head><title>Company</title></head><body><div itemscope itemtype="https://schema.org/Organization"><span itemprop="name">Acme Corp</span><span itemprop="foundingDate">2020</span><span itemprop="url">https://acmecorp.example.com</span><span itemprop="logo">https://acmecorp.example.com/logo.png</span></div></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataMicrodataSchemaPerson(t *testing.T) {
	// Extract schema.org microdata for Person
	err := htmd.Convert(`<html><head><title>Contact</title></head><body><div itemscope itemtype="https://schema.org/Person"><span itemprop="name">John Smith</span><span itemprop="email">john@example.com</span><span itemprop="telephone">+1-555-0100</span></div></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataMicrodataSchemaProduct(t *testing.T) {
	// Extract schema.org microdata for Product
	err := htmd.Convert(`<html><head><title>Product</title></head><body><div itemscope itemtype="https://schema.org/Product"><h1 itemprop="name">Awesome Widget</h1><span itemprop="description">The best widget on the market</span><span itemprop="price">29.99</span><span itemprop="priceCurrency">USD</span><img itemprop="image" src="widget.jpg" alt="Widget"><span itemprop="ratingValue">4.5</span></div></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataTextDirectionLtr(t *testing.T) {
	// Extract text direction from lang attribute on html element
	err := htmd.Convert(`<html lang="en" dir="ltr"><head><title>LTR Document</title></head><body><p>This is left-to-right text.</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataTextDirectionRtl(t *testing.T) {
	// Extract right-to-left text direction
	err := htmd.Convert(`<html lang="ar" dir="rtl"><head><title>RTL Document</title></head><body><p>This is right-to-left text.</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_MetadataTitleTag(t *testing.T) {
	// Extract title from <title> tag
	err := htmd.Convert(`<html><head><title>My Page</title></head><body><p>Content</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OgBasicTags(t *testing.T) {
	// Extract og:title, og:description, and og:image from Open Graph meta tags
	err := htmd.Convert(`<html><head><title>Fallback Title</title><meta property="og:title" content="OG Title"><meta property="og:description" content="OG description text."><meta property="og:image" content="https://example.com/image.jpg"></head><body><p>Content</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OgMultipleTags(t *testing.T) {
	// Extract multiple Open Graph tags including type, url, and site_name
	err := htmd.Convert(`<html><head><meta property="og:title" content="Article Title"><meta property="og:type" content="article"><meta property="og:url" content="https://example.com/article"><meta property="og:site_name" content="Example Site"><meta property="og:description" content="An interesting article."><meta property="og:image" content="https://example.com/article.jpg"></head><body><article><p>Article content here.</p></article></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StructuredDataJsonLd(t *testing.T) {
	// JSON-LD script tag is stripped from output (security) but metadata may be extracted
	err := htmd.Convert(`<html><head><title>Article</title><script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"My Article","author":{"@type":"Person","name":"Jane Doe"},"datePublished":"2024-01-15"}</script></head><body><h1>My Article</h1><p>Article body text.</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StructuredDataMultipleJsonLd(t *testing.T) {
	// Multiple JSON-LD blocks are all stripped from output
	err := htmd.Convert(`<html><head><title>Shop Page</title><script type="application/ld+json">{"@context":"https://schema.org","@type":"Product","name":"Widget","price":"9.99"}</script><script type="application/ld+json">{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home"}]}</script></head><body><h1>Widget</h1><p>A great widget for all purposes.</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_TwitterCardTags(t *testing.T) {
	// Extract Twitter card meta tags
	err := htmd.Convert(`<html><head><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="@examplesite"><meta name="twitter:title" content="Twitter Card Title"><meta name="twitter:description" content="Twitter card description."><meta name="twitter:image" content="https://example.com/twitter-image.jpg"></head><body><p>Content</p></body></html>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
