// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4b09aa0411986b55f34577d2949b6a4794a30aad6c8f5c8c8d49daa64e593fb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: options
package e2e_test

import (
	"encoding/json"
	"strings"
	"testing"

	htmd "github.com/kreuzberg-dev/html-to-markdown/packages/go/v3"
)

func Test_OptionsAutolinksFalse(t *testing.T) {
	// Bare URL links rendered as regular markdown links when autolinks disabled
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"autolinks":false}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p><a href='https://example.com'>https://example.com</a></p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsBrInTablesFalse(t *testing.T) {
	// BR elements in table cells are stripped when disabled
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"brInTables":false}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<table><tr><th>Col</th></tr><tr><td>A<br>B</td></tr></table>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsBrInTablesTrue(t *testing.T) {
	// BR elements in table cells render as line breaks
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"brInTables":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<table><tr><th>Header</th></tr><tr><td>Line 1<br>Line 2</td></tr></table>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsCodeBlockBackticks(t *testing.T) {
	// Backticks code block style uses triple backtick fences
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"codeBlockStyle":"Backticks"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<pre><code class="language-js">console.log('hi');</code></pre>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsCodeBlockIndented(t *testing.T) {
	// Code blocks use 4-space indentation
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"codeBlockStyle":"Indented"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<pre><code>print('hello')</code></pre>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsCodeBlockTildes(t *testing.T) {
	// Code blocks use tilde fences
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"codeBlockStyle":"Tildes"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<pre><code>let x = 1;</code></pre>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsCodeBlockTildesStyle(t *testing.T) {
	// Tildes code block style uses triple tilde fences
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"codeBlockStyle":"Tildes"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<pre><code>some code</code></pre>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsCodeLanguagePython(t *testing.T) {
	// Default code language annotation on blocks without lang attribute
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"codeLanguage":"python"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<pre><code>def hello(): pass</code></pre>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsConvertAsInline(t *testing.T) {
	// Block elements treated as inline
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"convertAsInline":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>One</p><p>Two</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsDebugTrue(t *testing.T) {
	// Debug mode enabled does not crash and produces output
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"debug":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Debug test</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsDefaultTitleTrue(t *testing.T) {
	// Links without title get empty title attribute when defaultTitle is true
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"defaultTitle":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p><a href='https://example.com'>Link</a></p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsEncodingUtf8(t *testing.T) {
	// UTF-8 encoding hint for special characters
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"encoding":"utf-8"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Café naïve résumé</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsEscapeAsciiEnabled(t *testing.T) {
	// ASCII Markdown characters are escaped when escapeAscii is true
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"escapeAscii":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Text with # hash and [brackets] and * star</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsEscapeAsterisks(t *testing.T) {
	// escape_asterisks option escapes asterisks in plain text
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"escapeAsterisks":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Use 2*3 = 6 in math.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsEscapeMisc(t *testing.T) {
	// escape_misc option escapes miscellaneous markdown characters
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"escapeMisc":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Use # and | and ~ in text.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsEscapeUnderscores(t *testing.T) {
	// escape_underscores option escapes underscores in plain text
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"escapeUnderscores":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>The variable_name is defined.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExcludeSelectorsAttribute(t *testing.T) {
	// Elements matching CSS attribute selector are excluded entirely
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"excludeSelectors":["[role='complementary']"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<body><div role="complementary">Sidebar</div><p>Primary text</p></body>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExcludeSelectorsClass(t *testing.T) {
	// Elements matching CSS class selector are excluded entirely
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"excludeSelectors":[".cookie-banner"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<body><div class="cookie-banner">Accept cookies</div><p>Main content</p></body>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExcludeSelectorsEmptyNoop(t *testing.T) {
	// Empty exclude_selectors list does not affect output
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"excludeSelectors":[]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Hello world</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExcludeSelectorsId(t *testing.T) {
	// Elements matching CSS id selector are excluded entirely
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"excludeSelectors":["#ad-container"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<body><div id="ad-container">Buy stuff</div><p>Article text</p></body>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExcludeSelectorsMultiple(t *testing.T) {
	// Multiple CSS selectors each exclude their matched elements
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"excludeSelectors":[".nav","footer"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<body><nav class="nav">Menu</nav><p>Content</p><footer>Footer</footer></body>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExcludeSelectorsNestedContentDropped(t *testing.T) {
	// All descendants of excluded elements are dropped
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"excludeSelectors":[".sidebar"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<body><aside class="sidebar"><h2>Related</h2><p>Sidebar text</p></aside><main><p>Main text</p></main></body>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExcludeSelectorsPlainTextMode(t *testing.T) {
	// Exclude selectors work in plain text output mode
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"excludeSelectors":[".nav"],"outputFormat":"Plain"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<body><div class="nav">Navigation</div><p>Article body</p></body>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExcludeSelectorsVsStripTags(t *testing.T) {
	// exclude_selectors drops entire subtree unlike strip_tags which keeps children
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"excludeSelectors":[".wrapper"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<body><div class="wrapper"><p>Inner paragraph</p></div><p>Outer text</p></body>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsExtractMetadataTrue(t *testing.T) {
	// Extract metadata returns document metadata when enabled
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"extractMetadata":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<html><head><title>Test Page</title><meta name='description' content='A test page'></head><body><p>Content</p></body></html>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsHeadingStyleAtx(t *testing.T) {
	// ATX heading style produces hash-prefixed headings
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"headingStyle":"Atx"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Title</h1><h2>Subtitle</h2>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsHeadingStyleAtxClosed(t *testing.T) {
	// ATX closed heading style adds closing hashes
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"headingStyle":"AtxClosed"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Closed Heading</h1>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsHeadingStyleUnderlined(t *testing.T) {
	// Underlined heading style produces setext-style headings for h1 and h2
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"headingStyle":"Underlined"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Main Title</h1>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsHighlightBold(t *testing.T) {
	// Mark tag rendered as bold
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"highlightStyle":"Bold"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Text with <mark>highlighted</mark> text.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsHighlightDoubleEqual(t *testing.T) {
	// Mark tag with double equal highlight style
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"highlightStyle":"DoubleEqual"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Text with <mark>highlighted</mark> here.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsHighlightNone(t *testing.T) {
	// Mark tag with no highlight style strips the mark
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"highlightStyle":"None"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Text with <mark>plain</mark> content.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsKeepInlineImagesInParagraph(t *testing.T) {
	// Images inside specified tags stay inline
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"keepInlineImagesIn":["p"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Text <img src='icon.png' alt='icon'> more text</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsLinkStyleReference(t *testing.T) {
	// Links use reference-style formatting
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"linkStyle":"Reference"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p><a href='https://example.com'>Example</a> and <a href='https://other.com'>Other</a></p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsListCustomBullets(t *testing.T) {
	// Custom bullet character for unordered lists
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"bullets":"*"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<ul><li>Item A</li><li>Item B</li></ul>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsListIndentTabs(t *testing.T) {
	// Tab indentation type for nested list items
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"listIndentType":"Tabs"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<ul><li>Parent<ul><li>Child</li></ul></li></ul>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsListIndentWidthFour(t *testing.T) {
	// Nested lists indented with 4 spaces per level
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"listIndentWidth":4}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<ul><li>Outer<ul><li>Inner</li></ul></li></ul>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsMaxDepthDefaultUnlimited(t *testing.T) {
	// Default max_depth (null) converts deeply nested content fully
	err := htmd.Convert(`<div><div><div><div><p>Deep content</p></div></div></div></div>`, htmd.ConversionOptions{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsMaxDepthTruncates(t *testing.T) {
	// max_depth truncates content beyond the specified depth
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"maxDepth":3}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<div><p>Shallow</p><div><div><div><p>Too deep</p></div></div></div></div>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsMaxDepthZeroEmpty(t *testing.T) {
	// max_depth of 0 produces empty output
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"maxDepth":0}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Hello</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsNewlineBackslash(t *testing.T) {
	// Hard line breaks rendered with backslash
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"newlineStyle":"Backslash"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Line one<br>Line two</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsNewlineSpaces(t *testing.T) {
	// Hard line breaks rendered with trailing spaces
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"newlineStyle":"Spaces"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>First<br>Second</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsOutputFormatDjot(t *testing.T) {
	// Djot output format produces djot-compatible markup
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"outputFormat":"Djot"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Simple paragraph.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsOutputFormatMarkdown(t *testing.T) {
	// Default markdown output format produces standard markdown
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"headingStyle":"Atx","outputFormat":"Markdown"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Title</h1><p>Some text.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsOutputFormatPlain(t *testing.T) {
	// Plain text output format strips markdown syntax
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"outputFormat":"Plain"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Title</h1><p>Some <strong>bold</strong> text.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsPreprocessingAggressive(t *testing.T) {
	// Aggressive preset removes nav, footer, aside unconditionally
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"preprocessing":{"preset":"Aggressive"}}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<nav>Menu</nav><article><h1>Title</h1><p>Content</p></article><aside>Sidebar</aside><footer>Footer</footer>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsPreprocessingMinimal(t *testing.T) {
	// Minimal preset preserves nav, footer, aside
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"preprocessing":{"preset":"Minimal"}}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<nav>Navigation</nav><p>Content</p><footer>Footer</footer>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsPreprocessingRemoveForms(t *testing.T) {
	// Forms are removed when remove_forms is true
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"preprocessing":{"removeForms":true}}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Before</p><form><input type='text'/><button>Submit</button></form><p>After</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsPreserveTagsIframe(t *testing.T) {
	// Iframe tags preserved as raw HTML in output
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"preserveTags":["iframe"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Before</p><iframe src='video.html' width='560'></iframe><p>After</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsSkipImagesTrue(t *testing.T) {
	// Images are omitted from output when skipImages is true
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"skipImages":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Before <img src='test.jpg' alt='photo'> After</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsStripNewlines(t *testing.T) {
	// Strip newlines produces single-line paragraphs
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"stripNewlines":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>First paragraph.</p><p>Second paragraph.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsStripTagsDivSpan(t *testing.T) {
	// Div and span tags stripped but content preserved
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"stripTags":["div","span"]}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<div class='wrapper'><p>Inside div</p></div><p>Outside <span class='hl'>span text</span></p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsStrongEmUnderscore(t *testing.T) {
	// Strong and em tags use underscore symbol instead of asterisk
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"strongEmSymbol":"_"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p><strong>bold</strong> and <em>italic</em></p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsSubSymbolTilde(t *testing.T) {
	// Subscript rendered with tilde symbol
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"subSymbol":"~"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>H<sub>2</sub>O</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsSupSymbolCaret(t *testing.T) {
	// Superscript rendered with caret symbol
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"supSymbol":"^"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>x<sup>2</sup></p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsWhitespaceNormalized(t *testing.T) {
	// Normalized whitespace mode collapses multiple spaces
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"whitespaceMode":"Normalized"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Text   with    extra   spaces.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsWhitespaceStrict(t *testing.T) {
	// Strict whitespace mode preserves whitespace as-is
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"whitespaceMode":"Strict"}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Preserved   spacing.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsWrapDisabled(t *testing.T) {
	// Wrap option disabled preserves long lines without breaking
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"wrap":false}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>This is a long paragraph that should not be wrapped at all because wrapping is disabled.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OptionsWrapEnabled(t *testing.T) {
	// Wrap option enabled with custom width wraps long lines
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"wrap":true,"wrapWidth":40}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>This is a long paragraph that should be wrapped at the specified column width when the wrap option is enabled.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
