// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:11c81ae51662618cb5675e635f653b0d02d2518e0d4510d2228256664d779ac2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: structure
package e2e_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"

	htmd "github.com/kreuzberg-dev/html-to-markdown/packages/go/v3"
)

func Test_StructureCodeBlock(t *testing.T) {
	// Fenced code block produces Code node
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"includeDocumentStructure":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Example code:</p><pre><code class="language-rust">fn main() { println!("Hello"); }</code></pre>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StructureDeepNestingH1H2H3(t *testing.T) {
	// H1 > H2 > H3 creates three levels of heading nesting
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"includeDocumentStructure":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Top Level</h1><p>Top intro.</p><h2>Mid Level</h2><p>Mid content.</p><h3>Deep Level</h3><p>Deep content.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StructureH1H2NestedGroup(t *testing.T) {
	// H1 followed by H2 creates a nested group under the H1
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"includeDocumentStructure":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Chapter One</h1><p>Chapter intro.</p><h2>Section One</h2><p>Section content.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StructureHeadingParagraph(t *testing.T) {
	// Simple heading followed by paragraph produces Heading and Paragraph nodes
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"includeDocumentStructure":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Title</h1><p>A paragraph of text.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StructureList(t *testing.T) {
	// Unordered list produces List and ListItem nodes
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"includeDocumentStructure":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<p>Items:</p><ul><li>Alpha</li><li>Beta</li><li>Gamma</li></ul>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StructureMultipleHeadings(t *testing.T) {
	// Multiple headings create multiple Heading nodes with correct levels
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"includeDocumentStructure":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Main Title</h1><h2>Section One</h2><p>Section one content.</p><h2>Section Two</h2><p>Section two content.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_StructureSiblingH1Groups(t *testing.T) {
	// H1, H2, then another H1 creates two sibling top-level groups
	var options htmd.ConversionOptions
	if err := json.Unmarshal([]byte(`{"includeDocumentStructure":true}`), &options); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	err := htmd.Convert(`<h1>Chapter One</h1><h2>Section A</h2><p>Section A content.</p><h1>Chapter Two</h1><h2>Section B</h2><p>Section B content.</p>`, options)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
