// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4e29cb370883e4545218e6912c522b1ec557173f12e737e77751ad37590bf2bd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: smoke

use html_to_markdown_rs::convert;

#[test]
fn test_smoke_empty_string() {
    // Empty string produces empty output
    let html = r#""#;
    let options = Default::default();
    let result = convert(html, &options);
    let content = result.content.as_deref().unwrap_or("");
    assert_eq!(content.trim(), r#""#, "equals assertion failed");
}

#[test]
fn test_smoke_simple_heading() {
    // H1 heading converts to ATX markdown
    let html = r#"<h1>Title</h1>"#;
    let options = Default::default();
    let result = convert(html, &options);
    let content = result.content.as_deref().unwrap_or("");
    assert!(
        format!("{:?}", content).contains(r#"# Title"#),
        "expected to contain: {}",
        r#"# Title"#
    );
}

#[test]
fn test_smoke_simple_paragraph() {
    // Simple paragraph converts correctly
    let html = r#"<p>Hello World</p>"#;
    let options = Default::default();
    let result = convert(html, &options);
    let content = result.content.as_deref().unwrap_or("");
    assert_eq!(content.trim(), r#"Hello World"#, "equals assertion failed");
    assert!(!content.is_empty(), "expected non-empty value");
}
